import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { BirthDetails } from '../components/BirthDetailsForm';

interface ExportData {
  birthDetails: BirthDetails;
  chartData: any;
  title?: string;
}

export async function exportChartToPDF(data: ExportData): Promise<void> {
  const { birthDetails, chartData, title = 'Kundli Chart' } = data;

  // Create PDF
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  let yPos = 20;

  // Title
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Divider
  pdf.setDrawColor(102, 126, 234);
  pdf.setLineWidth(0.5);
  pdf.line(20, yPos, pageWidth - 20, yPos);
  yPos += 10;

  // Birth Details Section
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Birth Details', 20, yPos);
  yPos += 8;

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  
  const birthInfo = [
    `Date: ${birthDetails.date}`,
    `Time: ${birthDetails.time}`,
    `Location: ${birthDetails.locationName}`,
    `Coordinates: ${birthDetails.latitude}°N, ${birthDetails.longitude}°E`,
    `Timezone: ${birthDetails.timezone}`,
    `Ayanamsa: ${birthDetails.ayanamsa_type}`,
    `House System: ${birthDetails.house_system}`,
  ];

  birthInfo.forEach(line => {
    pdf.text(line, 25, yPos);
    yPos += 6;
  });

  yPos += 5;

  // Ascendant and Key Info
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Chart Information', 20, yPos);
  yPos += 8;

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  
  if (chartData?.houses?.ascendant) {
    pdf.text(`Ascendant (Lagna): ${chartData.houses.ascendant.sign}`, 25, yPos);
    yPos += 6;
    pdf.text(`Ascendant Degree: ${chartData.houses.ascendant.longitude.toFixed(2)}°`, 25, yPos);
    yPos += 10;
  }

  // Planetary Positions
  if (chartData?.planetary_positions) {
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Planetary Positions', 20, yPos);
    yPos += 8;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');

    // Table header
    pdf.setFont('helvetica', 'bold');
    pdf.text('Planet', 25, yPos);
    pdf.text('Sign', 70, yPos);
    pdf.text('Degree', 120, yPos);
    pdf.text('House', 160, yPos);
    yPos += 6;

    // Table divider
    pdf.setDrawColor(200, 200, 200);
    pdf.line(20, yPos - 2, pageWidth - 20, yPos - 2);
    yPos += 2;

    pdf.setFont('helvetica', 'normal');

    Object.entries(chartData.planetary_positions).forEach(([name, planet]: [string, any]) => {
      if (yPos > pageHeight - 30) {
        pdf.addPage();
        yPos = 20;
      }

      pdf.text(name, 25, yPos);
      pdf.text(planet.sign, 70, yPos);
      pdf.text(`${planet.longitude.toFixed(2)}°`, 120, yPos);
      pdf.text(`${planet.house || 'N/A'}`, 160, yPos);
      yPos += 6;
    });
  }

  // Footer
  const currentDate = new Date().toLocaleDateString();
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text(`Generated by Kundli Calculator on ${currentDate}`, pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save PDF
  const filename = `${title.replace(/\s+/g, '_')}_${birthDetails.date}.pdf`;
  pdf.save(filename);
}

export async function exportChartWithImage(
  chartElement: HTMLElement,
  data: ExportData
): Promise<void> {
  const { birthDetails, chartData, title = 'Kundli Chart' } = data;

  // Create PDF
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  let yPos = 20;

  // Title
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Divider
  pdf.setDrawColor(102, 126, 234);
  pdf.setLineWidth(0.5);
  pdf.line(20, yPos, pageWidth - 20, yPos);
  yPos += 10;

  // Birth Details Section
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Birth Details', 20, yPos);
  yPos += 7;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  const birthInfo = [
    `Date: ${birthDetails.date} | Time: ${birthDetails.time}`,
    `Location: ${birthDetails.locationName}`,
    `Coordinates: ${birthDetails.latitude}°N, ${birthDetails.longitude}°E`,
  ];

  birthInfo.forEach(line => {
    pdf.text(line, 25, yPos);
    yPos += 5;
  });

  yPos += 8;

  // Capture chart as image
  try {
    const canvas = await html2canvas(chartElement, {
      scale: 2,
      backgroundColor: '#ffffff',
    });

    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 160;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    // Center the image
    const xPos = (pageWidth - imgWidth) / 2;

    pdf.addImage(imgData, 'PNG', xPos, yPos, imgWidth, imgHeight);
    yPos += imgHeight + 10;

    // If there's space, add planetary positions
    if (yPos < pageHeight - 80 && chartData?.planetary_positions) {
      pdf.addPage();
      yPos = 20;

      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Planetary Positions', 20, yPos);
      yPos += 8;

      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Planet', 25, yPos);
      pdf.text('Sign', 70, yPos);
      pdf.text('Degree', 115, yPos);
      pdf.text('House', 155, yPos);
      yPos += 5;

      pdf.setFont('helvetica', 'normal');

      Object.entries(chartData.planetary_positions).forEach(([name, planet]: [string, any]) => {
        if (yPos > pageHeight - 30) {
          pdf.addPage();
          yPos = 20;
        }

        pdf.text(name, 25, yPos);
        pdf.text(planet.sign, 70, yPos);
        pdf.text(`${planet.longitude.toFixed(2)}°`, 115, yPos);
        pdf.text(`${planet.house || 'N/A'}`, 155, yPos);
        yPos += 5;
      });
    }

    // Footer
    const currentDate = new Date().toLocaleDateString();
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(`Generated by Kundli Calculator on ${currentDate}`, pageWidth / 2, pageHeight - 10, { align: 'center' });

    // Save PDF
    const filename = `${title.replace(/\s+/g, '_')}_${birthDetails.date}.pdf`;
    pdf.save(filename);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
}
