"""
Hora Sara: Planets in Houses
==============================
Digitized interpretations from Hora Sara by Prithuyasas
Detailed planet-in-house analysis

Translation: R. Santhanam (1996)
Source: Ranjan Publications

Hora Sara provides detailed predictive interpretations for planetary placements.
"""

from typing import Any, Dict

HORA_SARA_PLANETS_IN_HOUSES: Dict[str, Dict[int, Dict[str, Any]]] = {
    "Sun": {
        1: {
            "chapter": 7,
            "verses": "7.1-2",
            "translation": "If the Sun occupies the ascendant, the native will have a lean body, be courageous, will have weak eyes, be valorous, firm in his decisions, will have weak hair, be impatient, and will have a bilious temperament.",
            "detailed_effects": [
                "Lean and athletic body type",
                "Courageous and brave nature",
                "Weak eyesight or eye problems",
                "Valorous and heroic",
                "Firm and decisive",
                "Thin or weak hair",
                "Impatient temperament",
                "Bilious constitution (Pitta dominant)",
            ],
            "positive_effects": ["Courage and valor", "Firm decision-making", "Athletic build", "Leadership qualities"],
            "challenging_effects": ["Weak eyes", "Impatience", "Hair problems", "Bilious health issues"],
            "timing": "Physical traits manifest from birth, leadership develops with age",
            "tags": ["personality", "health", "courage", "appearance"],
            "confidence": "high",
            "notes": "Hora Sara provides detailed physical and temperamental descriptions",
        },
        2: {
            "chapter": 7,
            "verses": "7.3",
            "translation": "The Sun in the 2nd house makes one learned in Shastras, will have an angry disposition, will serve others, will have a diseased face, and will be devoid of wealth and happiness.",
            "detailed_effects": [
                "Learned in scriptures and philosophy",
                "Angry and wrathful temperament",
                "Service to others or employers",
                "Facial health issues",
                "Financial struggles",
                "Lack of happiness",
            ],
            "positive_effects": ["Scholarly knowledge", "Service-oriented"],
            "challenging_effects": ["Anger problems", "Facial diseases", "Financial difficulties", "Unhappiness"],
            "timing": "Learning throughout life, financial struggles persistent",
            "tags": ["wealth", "speech", "education", "health"],
            "confidence": "high",
        },
        3: {
            "chapter": 7,
            "verses": "7.4",
            "translation": "With the Sun in the 3rd house, one will be valorous, strong, will lose co-born, be liberal, charitable, and will have good qualities.",
            "detailed_effects": [
                "Valorous and courageous",
                "Physical strength",
                "Loss of siblings or strained relations",
                "Liberal and generous nature",
                "Charitable disposition",
                "Good moral qualities",
            ],
            "positive_effects": ["Valor and courage", "Physical strength", "Generosity", "Charity", "Good character"],
            "challenging_effects": ["Loss of siblings", "Sibling conflicts"],
            "timing": "Courage throughout life, sibling issues in youth",
            "tags": ["courage", "siblings", "character", "charity"],
            "confidence": "high",
        },
        4: {
            "chapter": 7,
            "verses": "7.5",
            "translation": "If the Sun is in the 4th house, one will be devoid of conveyances and relatives, will suffer heart diseases, will destroy paternal house and wealth, and will serve a bad king.",
            "detailed_effects": [
                "Lack of vehicles",
                "Few relatives or isolation",
                "Heart and cardiac problems",
                "Destruction of father's property",
                "Loss of paternal wealth",
                "Service under difficult authority",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "No vehicles",
                "Social isolation",
                "Heart disease",
                "Property losses",
                "Difficult employment",
            ],
            "timing": "Property issues throughout, heart health concerns in middle age",
            "tags": ["mother", "property", "health", "vehicles"],
            "confidence": "high",
            "notes": "Sun in 4th (Maraka house) gives multiple challenges",
        },
        5: {
            "chapter": 7,
            "verses": "7.6",
            "translation": "The Sun in the 5th house denotes that one will be bereft of happiness, wealth, and sons, will live in foreign places, be intelligent, and will have heart diseases.",
            "detailed_effects": [
                "Lack of happiness",
                "Financial difficulties",
                "Issues with children or childlessness",
                "Life in foreign lands",
                "High intelligence",
                "Heart and cardiac problems",
            ],
            "positive_effects": ["High intelligence", "Foreign opportunities"],
            "challenging_effects": ["Unhappiness", "Poverty", "Children problems", "Heart disease"],
            "timing": "Children issues during procreative years, intelligence throughout",
            "tags": ["children", "intelligence", "wealth", "health"],
            "confidence": "high",
        },
        6: {
            "chapter": 7,
            "verses": "7.7",
            "translation": "If the Sun occupies the 6th house, one will be very strong, will be a king or equal to a king, will have enmity with his relatives, and will conquer his enemies.",
            "detailed_effects": [
                "Exceptional physical strength",
                "Authority and leadership (king-like)",
                "Conflicts with relatives",
                "Victory over enemies",
                "Power and dominance",
            ],
            "positive_effects": ["Physical strength", "Authority and power", "Victory over enemies", "Leadership"],
            "challenging_effects": ["Relative conflicts", "Family enmity"],
            "timing": "Strength throughout life, authority in career years",
            "tags": ["health", "enemies", "authority", "relatives"],
            "confidence": "high",
            "notes": "Sun in 6th (Upachaya) gives strength and victory",
        },
        7: {
            "chapter": 7,
            "verses": "7.8",
            "translation": "The Sun in the 7th house makes one suffer from diseases, will have a diseased wife, be devoid of wealth, will wander, and will suffer humiliation.",
            "detailed_effects": [
                "Chronic health problems",
                "Spouse with health issues",
                "Financial losses",
                "Wandering or travel",
                "Loss of dignity and respect",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Health problems",
                "Spouse's ill health",
                "Poverty",
                "Wandering life",
                "Humiliation",
            ],
            "timing": "Marital and health issues after marriage",
            "tags": ["marriage", "health", "wealth", "dignity"],
            "confidence": "high",
        },
        8: {
            "chapter": 7,
            "verses": "7.9",
            "translation": "With the Sun in the 8th house, one will have defective eyes, be devoid of wealth and happiness, will suffer from diseases, and will have a short life.",
            "detailed_effects": [
                "Eye defects or blindness",
                "Poverty and financial struggles",
                "Lack of happiness",
                "Chronic diseases",
                "Reduced longevity",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Eye problems",
                "Financial losses",
                "Unhappiness",
                "Health issues",
                "Short lifespan",
            ],
            "timing": "Multiple challenges throughout life",
            "tags": ["longevity", "wealth", "health", "eyes"],
            "confidence": "high",
            "notes": "Sun in 8th (Dusthana) gives severe afflictions",
        },
        9: {
            "chapter": 7,
            "verses": "7.10",
            "translation": "If the Sun is in the 9th house, one will be devoid of wealth, children, and happiness, will be irreligious, and will lose his father.",
            "detailed_effects": [
                "Financial difficulties",
                "Issues with children",
                "Lack of happiness",
                "Irreligious tendencies",
                "Loss of father or conflict",
            ],
            "positive_effects": [],
            "challenging_effects": ["Poverty", "Children problems", "Unhappiness", "Lack of dharma", "Father's loss"],
            "timing": "Father-related effects in youth, dharma issues throughout",
            "tags": ["dharma", "father", "children", "wealth"],
            "confidence": "high",
        },
        10: {
            "chapter": 7,
            "verses": "7.11",
            "translation": "The Sun in the 10th house makes one learned, will perform good acts, be a king or minister, will have sons, be virtuous, and will have conveyances.",
            "detailed_effects": [
                "Scholarly and learned",
                "Virtuous actions",
                "Authority position (king/minister)",
                "Good children",
                "Virtuous character",
                "Vehicles and conveyances",
            ],
            "positive_effects": ["Learning and wisdom", "Authority and power", "Good progeny", "Virtue", "Vehicles"],
            "challenging_effects": [],
            "timing": "Career success throughout, authority in middle age",
            "tags": ["career", "authority", "virtue", "children"],
            "confidence": "high",
            "notes": "Sun in 10th (own house) is very strong and auspicious",
        },
        11: {
            "chapter": 7,
            "verses": "7.12",
            "translation": "If the Sun occupies the 11th house, one will be long-lived, will have abundant wealth, be endowed with sons, be happy, and will have limited diseases.",
            "detailed_effects": [
                "Long lifespan",
                "Abundant wealth and gains",
                "Good children",
                "Overall happiness",
                "Strong health with minimal diseases",
            ],
            "positive_effects": ["Longevity", "Wealth and gains", "Good progeny", "Happiness", "Good health"],
            "challenging_effects": [],
            "timing": "Gains throughout life, peak during Sun dasha",
            "tags": ["wealth", "gains", "longevity", "children"],
            "confidence": "high",
            "notes": "Sun in 11th (Upachaya/gains) is very favorable",
        },
        12: {
            "chapter": 7,
            "verses": "7.13",
            "translation": "The Sun in the 12th house makes one have defective eyes, be devoid of wealth, will have limited sons, be inimical to his father, and will have a weak body.",
            "detailed_effects": [
                "Eye defects or vision problems",
                "Poverty and financial losses",
                "Few children or childlessness",
                "Conflict with father",
                "Weak physical constitution",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Eye problems",
                "Financial losses",
                "Children issues",
                "Father conflicts",
                "Weak health",
            ],
            "timing": "Multiple challenges throughout life",
            "tags": ["losses", "health", "father", "children"],
            "confidence": "high",
            "notes": "Sun in 12th (Dusthana/losses) gives multiple afflictions",
        },
    },
    "Moon": {
        1: {
            "chapter": 8,
            "verses": "8.1",
            "translation": "Moon in 1st makes one fickle-minded, handsome, with beautiful eyes, fond of water, kind-hearted, and soft-spoken.",
            "detailed_effects": [
                "Fickle and changeable mind",
                "Handsome appearance",
                "Beautiful eyes",
                "Love for water and liquids",
                "Kind and compassionate",
                "Soft and gentle speech",
            ],
            "positive_effects": ["Beauty", "Kind nature", "Soft speech", "Compassion"],
            "challenging_effects": ["Mental fickleness", "Changeable moods"],
            "timing": "Emotional patterns throughout life",
            "tags": ["personality", "appearance", "emotions", "temperament"],
            "confidence": "high",
        },
        4: {
            "chapter": 8,
            "verses": "8.4",
            "translation": "Moon in 4th gives happiness, mother's blessings, property, vehicles, comforts, and good friends.",
            "detailed_effects": [
                "Domestic happiness",
                "Mother's blessings and grace",
                "Property and land ownership",
                "Vehicles and conveyances",
                "Material comforts",
                "Good friendships",
            ],
            "positive_effects": ["Happiness", "Mother's grace", "Property", "Vehicles", "Comforts", "Friends"],
            "challenging_effects": [],
            "timing": "Property during Moon dasha, happiness throughout",
            "tags": ["mother", "property", "happiness", "vehicles"],
            "confidence": "high",
        },
        7: {
            "chapter": 8,
            "verses": "8.7",
            "translation": "Moon in 7th gives beautiful spouse, passionate nature, wealth, and happiness in marriage.",
            "detailed_effects": [
                "Beautiful and attractive spouse",
                "Passionate and romantic nature",
                "Wealth through marriage",
                "Marital happiness",
                "Emotional fulfillment",
            ],
            "positive_effects": ["Beautiful spouse", "Marital bliss", "Wealth", "Passion"],
            "challenging_effects": [],
            "timing": "Marriage during Moon dasha",
            "tags": ["marriage", "wealth", "happiness", "passion"],
            "confidence": "high",
        },
        10: {
            "chapter": 8,
            "verses": "8.10",
            "translation": "Moon in 10th gives success, intelligence, fame, virtue, and respect.",
            "detailed_effects": [
                "Professional success",
                "High intelligence",
                "Fame and recognition",
                "Virtuous character",
                "Social respect",
            ],
            "positive_effects": ["Career success", "Intelligence", "Fame", "Virtue", "Respect"],
            "challenging_effects": [],
            "timing": "Career success during Moon dasha",
            "tags": ["career", "fame", "intelligence", "virtue"],
            "confidence": "high",
        },
    },
    "Mars": {
        1: {
            "chapter": 9,
            "verses": "9.1",
            "translation": "Mars in 1st makes one cruel, adventurous, with scarred body, short-lived, valorous, and having bilious constitution.",
            "detailed_effects": [
                "Cruel or harsh nature",
                "Adventurous spirit",
                "Scars or marks on body",
                "Reduced longevity if afflicted",
                "Valorous and courageous",
                "Bilious (Pitta) constitution",
            ],
            "positive_effects": ["Courage and valor", "Adventurous nature", "Physical strength", "Leadership"],
            "challenging_effects": ["Cruel disposition", "Body scars", "Short lifespan", "Aggressive nature"],
            "timing": "Courage throughout life, health challenges",
            "tags": ["personality", "health", "courage", "longevity"],
            "confidence": "high",
        },
        2: {
            "chapter": 9,
            "verses": "9.2",
            "translation": "Mars in 2nd makes one poor, ugly-faced, harsh in speech, will eat bad food, and be devoid of learning.",
            "detailed_effects": [
                "Financial difficulties",
                "Unattractive facial features",
                "Harsh or aggressive speech",
                "Poor dietary habits",
                "Limited education",
                "Family conflicts",
            ],
            "positive_effects": ["Strong voice", "Assertive communication"],
            "challenging_effects": ["Poverty", "Ugly face", "Harsh speech", "Bad food", "Lack of learning"],
            "timing": "Financial struggles throughout life",
            "tags": ["wealth", "speech", "education", "appearance"],
            "confidence": "high",
        },
        3: {
            "chapter": 9,
            "verses": "9.3",
            "translation": "Mars in 3rd gives valor, strength, loss of siblings, liberal nature, and wealth.",
            "detailed_effects": [
                "Exceptional courage",
                "Physical strength",
                "Loss of or conflicts with siblings",
                "Liberal and generous",
                "Wealth through effort",
                "Initiative and drive",
            ],
            "positive_effects": ["Courage and valor", "Physical strength", "Generosity", "Wealth", "Initiative"],
            "challenging_effects": ["Sibling loss", "Conflicts with brothers/sisters"],
            "timing": "Courage evident early, wealth through effort",
            "tags": ["courage", "siblings", "wealth", "strength"],
            "confidence": "high",
        },
        4: {
            "chapter": 9,
            "verses": "9.4",
            "translation": "Mars in 4th causes lack of happiness, loss of relatives, property destruction, and heart diseases.",
            "detailed_effects": [
                "Domestic unhappiness",
                "Loss of relatives",
                "Property destruction or loss",
                "Heart and cardiac problems",
                "Mother's health issues",
                "Frequent residence changes",
            ],
            "positive_effects": ["Independence", "Self-reliance"],
            "challenging_effects": ["Unhappiness", "Relative loss", "Property destruction", "Heart disease"],
            "timing": "Domestic challenges throughout life",
            "tags": ["mother", "property", "health", "happiness"],
            "confidence": "high",
        },
        5: {
            "chapter": 9,
            "verses": "9.5",
            "translation": "Mars in 5th gives lack of children, financial difficulties, fickle mind, and stomach diseases.",
            "detailed_effects": [
                "Childlessness or delayed children",
                "Financial struggles",
                "Changeable mind",
                "Digestive problems",
                "Speculative losses",
                "Creative frustrations",
            ],
            "positive_effects": ["Intelligence", "Analytical ability"],
            "challenging_effects": ["No children", "Poverty", "Fickle mind", "Stomach diseases"],
            "timing": "Children issues, financial struggles",
            "tags": ["children", "wealth", "health", "mind"],
            "confidence": "high",
        },
        6: {
            "chapter": 9,
            "verses": "9.6",
            "translation": "Mars in 6th gives strength, victory over enemies, fame, but excessive sexual desires and wounds.",
            "detailed_effects": [
                "Exceptional strength",
                "Victory over enemies",
                "Fame and recognition",
                "Strong sexual drive",
                "Prone to injuries and wounds",
                "Success in competition",
            ],
            "positive_effects": ["Physical strength", "Defeats enemies", "Fame", "Competitive success"],
            "challenging_effects": ["Excessive libido", "Wounds and injuries", "Accidents"],
            "timing": "Victory over enemies, injuries possible",
            "tags": ["enemies", "health", "fame", "strength"],
            "confidence": "high",
        },
        7: {
            "chapter": 9,
            "verses": "9.7",
            "translation": "Mars in 7th causes loss of wife, diseases, sinful acts, and unhappiness.",
            "detailed_effects": [
                "Loss of spouse or separation",
                "Chronic diseases",
                "Sinful or unethical behavior",
                "Marital discord",
                "Unhappiness",
                "Partnership conflicts",
            ],
            "positive_effects": ["Passionate nature"],
            "challenging_effects": ["Loss of wife", "Diseases", "Sinful acts", "Unhappiness", "Marital problems"],
            "timing": "Marriage challenges throughout life",
            "tags": ["marriage", "health", "ethics", "happiness"],
            "confidence": "high",
        },
        8: {
            "chapter": 9,
            "verses": "9.8",
            "translation": "Mars in 8th gives eye defects, poverty, short life, and physical defects.",
            "detailed_effects": [
                "Eye problems or defects",
                "Poverty and financial loss",
                "Reduced longevity",
                "Physical deformities",
                "Chronic health issues",
                "Sudden accidents",
            ],
            "positive_effects": ["Interest in occult", "Research abilities"],
            "challenging_effects": ["Eye defects", "Poverty", "Short life", "Physical defects"],
            "timing": "Multiple health challenges throughout life",
            "tags": ["longevity", "health", "wealth", "eyes"],
            "confidence": "high",
        },
        9: {
            "chapter": 9,
            "verses": "9.9",
            "translation": "Mars in 9th makes one unskillful, with adverse wife, violent tendencies, and irreligious.",
            "detailed_effects": [
                "Lack of skills",
                "Difficult spouse",
                "Violent or aggressive tendencies",
                "Irreligious nature",
                "Father conflicts",
                "Lack of dharma",
            ],
            "positive_effects": ["Independent thinking"],
            "challenging_effects": ["Lack of skills", "Bad wife", "Violence", "Irreligious", "Father issues"],
            "timing": "Father-related conflicts, spiritual challenges",
            "tags": ["dharma", "father", "marriage", "ethics"],
            "confidence": "high",
        },
        10: {
            "chapter": 9,
            "verses": "9.10",
            "translation": "Mars in 10th gives authority, fame, valor, wealth, and success in career.",
            "detailed_effects": [
                "Authority and leadership",
                "Fame and recognition",
                "Valor and courage",
                "Wealth through career",
                "Success in competitive fields",
                "Military or technical career",
            ],
            "positive_effects": ["Authority", "Fame", "Valor", "Wealth", "Career success"],
            "challenging_effects": ["Aggressive career approach", "Conflicts with authority"],
            "timing": "Career success throughout, peak in Mars dasha",
            "tags": ["career", "authority", "fame", "wealth"],
            "confidence": "high",
        },
        11: {
            "chapter": 9,
            "verses": "9.11",
            "translation": "Mars in 11th gives wealth, longevity, limited children, and fulfillment of desires.",
            "detailed_effects": [
                "Wealth and gains",
                "Long life",
                "Few children",
                "Fulfillment of desires",
                "Social success",
                "Multiple income sources",
            ],
            "positive_effects": ["Wealth", "Longevity", "Achievement of goals", "Gains"],
            "challenging_effects": ["Limited children", "Aggressive in friendships"],
            "timing": "Gains increase with age",
            "tags": ["wealth", "gains", "longevity", "children"],
            "confidence": "high",
        },
        12: {
            "chapter": 9,
            "verses": "9.12",
            "translation": "Mars in 12th gives eye diseases, loss of position, poverty, and physical defects.",
            "detailed_effects": [
                "Eye diseases",
                "Loss of status or position",
                "Poverty and expenses",
                "Physical defects",
                "Financial losses",
                "Interest in foreign lands",
            ],
            "positive_effects": ["Courage in isolation", "Foreign opportunities"],
            "challenging_effects": ["Eye diseases", "Loss of position", "Poverty", "Physical defects"],
            "timing": "Expenses and losses throughout life",
            "tags": ["losses", "health", "wealth", "eyes"],
            "confidence": "high",
        },
    },
    "Mercury": {
        1: {
            "chapter": 10,
            "verses": "10.1",
            "translation": "Mercury in 1st makes one learned, sweet in speech, skillful, with self-earned wealth, and youthful appearance.",
            "detailed_effects": [
                "Highly intelligent",
                "Sweet and persuasive speech",
                "Skillful and versatile",
                "Self-made wealth",
                "Youthful appearance",
                "Quick learning",
            ],
            "positive_effects": ["Intelligence", "Sweet speech", "Skills", "Self-earned wealth", "Youthful looks"],
            "challenging_effects": ["Nervous energy", "Restlessness"],
            "timing": "Intelligence throughout life, business success",
            "tags": ["intelligence", "speech", "wealth", "appearance"],
            "confidence": "high",
        },
        2: {
            "chapter": 10,
            "verses": "10.2",
            "translation": "Mercury in 2nd gives wealth through intelligence, sweet speech, good food, and family happiness.",
            "detailed_effects": [
                "Wealth through intellect",
                "Sweet and effective speech",
                "Good food and dining",
                "Family happiness",
                "Business acumen",
                "Multiple income sources",
            ],
            "positive_effects": ["Wealth", "Sweet speech", "Good food", "Family harmony", "Business success"],
            "challenging_effects": ["Scattered financial focus"],
            "timing": "Wealth increases through intelligence",
            "tags": ["wealth", "speech", "family", "food"],
            "confidence": "high",
        },
        3: {
            "chapter": 10,
            "verses": "10.3",
            "translation": "Mercury in 3rd gives hard work, skillfulness, good siblings, cheerfulness, and success through effort.",
            "detailed_effects": [
                "Hard-working nature",
                "Skillful and versatile",
                "Good sibling relationships",
                "Cheerful disposition",
                "Success through effort",
                "Communication skills",
            ],
            "positive_effects": ["Skills", "Good siblings", "Cheerfulness", "Hard work", "Communication"],
            "challenging_effects": ["Constant effort required", "Restlessness"],
            "timing": "Success through persistent effort",
            "tags": ["siblings", "skills", "effort", "communication"],
            "confidence": "high",
        },
        4: {
            "chapter": 10,
            "verses": "10.4",
            "translation": "Mercury in 4th gives property, vehicles, learning, intelligence, and domestic happiness.",
            "detailed_effects": [
                "Property and land",
                "Vehicles and conveyances",
                "Good education",
                "High intelligence",
                "Domestic happiness",
                "Mother's blessings",
            ],
            "positive_effects": ["Property", "Vehicles", "Learning", "Intelligence", "Happiness"],
            "challenging_effects": ["Restless at home"],
            "timing": "Property during Mercury dasha",
            "tags": ["property", "vehicles", "education", "happiness"],
            "confidence": "high",
        },
        5: {
            "chapter": 10,
            "verses": "10.5",
            "translation": "Mercury in 5th gives good children, learning, skillfulness, and happiness.",
            "detailed_effects": [
                "Intelligent children",
                "Good education",
                "Skillful and versatile",
                "Happiness and joy",
                "Creative intelligence",
                "Success in speculation",
            ],
            "positive_effects": ["Good children", "Learning", "Skills", "Happiness", "Creativity"],
            "challenging_effects": ["Overthinking"],
            "timing": "Children during Mercury dasha",
            "tags": ["children", "education", "skills", "happiness"],
            "confidence": "high",
        },
        6: {
            "chapter": 10,
            "verses": "10.6",
            "translation": "Mercury in 6th gives enemies, poverty, harsh speech, and service to others.",
            "detailed_effects": [
                "Many enemies",
                "Financial difficulties",
                "Harsh or critical speech",
                "Service-oriented work",
                "Health issues from stress",
                "Analytical abilities",
            ],
            "positive_effects": ["Analytical skills", "Problem-solving", "Service success"],
            "challenging_effects": ["Enemies", "Poverty", "Harsh speech", "Service work"],
            "timing": "Enemies and financial challenges",
            "tags": ["enemies", "wealth", "speech", "service"],
            "confidence": "high",
        },
        7: {
            "chapter": 10,
            "verses": "10.7",
            "translation": "Mercury in 7th gives beautiful spouse, learning, wealth, and happiness in marriage.",
            "detailed_effects": [
                "Intelligent and beautiful spouse",
                "Good education",
                "Wealth through partnerships",
                "Marital happiness",
                "Business partnership success",
                "Diplomatic abilities",
            ],
            "positive_effects": ["Beautiful spouse", "Learning", "Wealth", "Marital happiness", "Partnership success"],
            "challenging_effects": ["Communication issues in marriage"],
            "timing": "Marriage during Mercury dasha",
            "tags": ["marriage", "wealth", "education", "partnerships"],
            "confidence": "high",
        },
        8: {
            "chapter": 10,
            "verses": "10.8",
            "translation": "Mercury in 8th gives fame, learning, longevity, and wealth.",
            "detailed_effects": [
                "Fame and recognition",
                "Deep learning",
                "Long life",
                "Wealth and prosperity",
                "Research abilities",
                "Occult knowledge",
            ],
            "positive_effects": ["Fame", "Learning", "Longevity", "Wealth", "Research skills"],
            "challenging_effects": ["Obsessive thinking"],
            "timing": "Fame and wealth in Mercury dasha",
            "tags": ["fame", "learning", "longevity", "wealth"],
            "confidence": "high",
        },
        9: {
            "chapter": 10,
            "verses": "10.9",
            "translation": "Mercury in 9th gives wealth, skills, fame, good spouse, children, and all learning.",
            "detailed_effects": [
                "Wealth and prosperity",
                "Skillful and versatile",
                "Fame and recognition",
                "Good spouse",
                "Good children",
                "Complete learning",
            ],
            "positive_effects": ["Wealth", "Skills", "Fame", "Good spouse", "Good children", "Learning"],
            "challenging_effects": [],
            "timing": "Fortune increases in Mercury dasha",
            "tags": ["wealth", "fame", "education", "fortune"],
            "confidence": "high",
        },
        10: {
            "chapter": 10,
            "verses": "10.10",
            "translation": "Mercury in 10th gives learning, fame, skillfulness, happiness from wife and children.",
            "detailed_effects": [
                "Learning and wisdom",
                "Fame and recognition",
                "Skillful in profession",
                "Happiness from spouse",
                "Happiness from children",
                "Career success",
            ],
            "positive_effects": ["Learning", "Fame", "Skills", "Family happiness", "Career success"],
            "challenging_effects": ["Scattered career focus"],
            "timing": "Career success in Mercury dasha",
            "tags": ["career", "fame", "education", "family"],
            "confidence": "high",
        },
        11: {
            "chapter": 10,
            "verses": "10.11",
            "translation": "Mercury in 11th gives wealth, longevity, limited children, and fulfillment of desires.",
            "detailed_effects": [
                "Wealth and gains",
                "Long life",
                "Few but intelligent children",
                "Fulfillment of desires",
                "Social success",
                "Multiple income sources",
            ],
            "positive_effects": ["Wealth", "Longevity", "Achievement of goals", "Gains"],
            "challenging_effects": ["Limited children"],
            "timing": "Gains increase with age",
            "tags": ["wealth", "gains", "longevity", "children"],
            "confidence": "high",
        },
        12: {
            "chapter": 10,
            "verses": "10.12",
            "translation": "Mercury in 12th gives learning, skills, good spouse, and happiness.",
            "detailed_effects": [
                "Learning and wisdom",
                "Skillful and versatile",
                "Good spouse",
                "Happiness and contentment",
                "Success in foreign lands",
                "Spiritual learning",
            ],
            "positive_effects": ["Learning", "Skills", "Good spouse", "Happiness", "Foreign success"],
            "challenging_effects": ["Expenses on education"],
            "timing": "Spiritual growth in Mercury dasha",
            "tags": ["education", "skills", "marriage", "foreign"],
            "confidence": "high",
        },
    },
    "Venus": {
        1: {
            "chapter": 11,
            "verses": "11.1",
            "translation": "Venus in 1st gives beauty, charming physique, happiness, longevity, and attractive eyes.",
            "detailed_effects": [
                "Physical beauty",
                "Charming personality",
                "Happiness and contentment",
                "Long life",
                "Attractive eyes",
                "Artistic nature",
            ],
            "positive_effects": ["Beauty", "Charm", "Happiness", "Longevity", "Attractive eyes"],
            "challenging_effects": ["May be vain"],
            "timing": "Beauty and happiness throughout life",
            "tags": ["beauty", "happiness", "longevity", "appearance"],
            "confidence": "high",
        },
        2: {
            "chapter": 11,
            "verses": "11.2",
            "translation": "Venus in 2nd gives wealth, poetic speech, beautiful face, and family happiness.",
            "detailed_effects": [
                "Wealth and prosperity",
                "Poetic and sweet speech",
                "Beautiful facial features",
                "Family happiness",
                "Artistic talents",
                "Good food",
            ],
            "positive_effects": ["Wealth", "Poetic speech", "Beautiful face", "Family harmony", "Arts"],
            "challenging_effects": ["Expenses on luxuries"],
            "timing": "Wealth increases in Venus dasha",
            "tags": ["wealth", "speech", "beauty", "family"],
            "confidence": "high",
        },
        3: {
            "chapter": 11,
            "verses": "11.3",
            "translation": "Venus in 3rd gives limited sibling happiness, miserly nature, beautiful spouse, and skills.",
            "detailed_effects": [
                "Limited happiness from siblings",
                "Frugal or miserly",
                "Beautiful spouse",
                "Artistic skills",
                "Success through effort",
                "Creative abilities",
            ],
            "positive_effects": ["Beautiful spouse", "Artistic skills", "Financial prudence"],
            "challenging_effects": ["Sibling issues", "Miserly nature"],
            "timing": "Artistic success in Venus dasha",
            "tags": ["siblings", "marriage", "skills", "arts"],
            "confidence": "high",
        },
        4: {
            "chapter": 11,
            "verses": "11.4",
            "translation": "Venus in 4th gives vehicles, garments, ornaments, and happiness from mother.",
            "detailed_effects": [
                "Vehicles and conveyances",
                "Beautiful clothes",
                "Ornaments and jewelry",
                "Mother's happiness",
                "Domestic comforts",
                "Property and land",
            ],
            "positive_effects": [
                "Vehicles",
                "Beautiful possessions",
                "Mother's grace",
                "Domestic happiness",
                "Comforts",
            ],
            "challenging_effects": ["Attachment to comforts"],
            "timing": "Vehicles and comforts in Venus dasha",
            "tags": ["vehicles", "mother", "comforts", "property"],
            "confidence": "high",
        },
        5: {
            "chapter": 11,
            "verses": "11.5",
            "translation": "Venus in 5th gives good children, happiness, intelligence, and enjoyment of pleasures.",
            "detailed_effects": [
                "Good and beautiful children",
                "Happiness and joy",
                "Intelligence and creativity",
                "Enjoyment of pleasures",
                "Romantic fulfillment",
                "Artistic talents",
            ],
            "positive_effects": ["Good children", "Happiness", "Intelligence", "Pleasures", "Romance"],
            "challenging_effects": ["Overindulgence"],
            "timing": "Children in Venus dasha",
            "tags": ["children", "happiness", "intelligence", "romance"],
            "confidence": "high",
        },
        6: {
            "chapter": 11,
            "verses": "11.6",
            "translation": "Venus in 6th gives no enemies, fame, beautiful spouse, and happiness.",
            "detailed_effects": [
                "No enemies or victory over them",
                "Fame and recognition",
                "Beautiful spouse",
                "Happiness and contentment",
                "Success in service",
                "Diplomatic abilities",
            ],
            "positive_effects": ["No enemies", "Fame", "Beautiful spouse", "Happiness", "Service success"],
            "challenging_effects": ["Health issues from indulgence"],
            "timing": "Victory over enemies in Venus dasha",
            "tags": ["enemies", "fame", "marriage", "happiness"],
            "confidence": "high",
        },
        7: {
            "chapter": 11,
            "verses": "11.7",
            "translation": "Venus in 7th gives beautiful spouse, sexual pleasures, virtue, and fame.",
            "detailed_effects": [
                "Beautiful and loving spouse",
                "Sexual fulfillment",
                "Virtuous character",
                "Fame and recognition",
                "Marital happiness",
                "Partnership success",
            ],
            "positive_effects": ["Beautiful spouse", "Sexual pleasures", "Virtue", "Fame", "Marital bliss"],
            "challenging_effects": ["Overindulgence in pleasures"],
            "timing": "Marriage in Venus dasha",
            "tags": ["marriage", "fame", "virtue", "happiness"],
            "confidence": "high",
        },
        8: {
            "chapter": 11,
            "verses": "11.8",
            "translation": "Venus in 8th gives longevity, limited wealth, and lack of happiness from spouse.",
            "detailed_effects": [
                "Long life",
                "Limited financial resources",
                "Marital challenges",
                "Interest in occult",
                "Transformative relationships",
                "Inheritance issues",
            ],
            "positive_effects": ["Longevity", "Occult knowledge", "Transformative growth"],
            "challenging_effects": ["Limited wealth", "Marital discord", "Unhappiness from spouse"],
            "timing": "Long life, marital challenges",
            "tags": ["longevity", "wealth", "marriage", "occult"],
            "confidence": "high",
        },
        9: {
            "chapter": 11,
            "verses": "11.9",
            "translation": "Venus in 9th gives devotion to dharma, happiness, wealth, and good children.",
            "detailed_effects": [
                "Devotion to father and dharma",
                "Happiness and contentment",
                "Wealth and prosperity",
                "Good children",
                "Artistic and creative talents",
                "Fortune and blessings",
            ],
            "positive_effects": ["Dharma devotion", "Happiness", "Wealth", "Good children", "Fortune"],
            "challenging_effects": ["Idealistic in beliefs"],
            "timing": "Fortune in Venus dasha",
            "tags": ["dharma", "happiness", "wealth", "children"],
            "confidence": "high",
        },
        10: {
            "chapter": 11,
            "verses": "11.10",
            "translation": "Venus in 10th gives authority, happiness, valor, and success.",
            "detailed_effects": [
                "Authority and leadership",
                "Happiness and contentment",
                "Valor and courage",
                "Career success",
                "Fame in artistic fields",
                "Diplomatic abilities",
            ],
            "positive_effects": ["Authority", "Happiness", "Valor", "Career success", "Fame"],
            "challenging_effects": ["Career focused on pleasures"],
            "timing": "Career success in Venus dasha",
            "tags": ["career", "authority", "happiness", "fame"],
            "confidence": "high",
        },
        11: {
            "chapter": 11,
            "verses": "11.11",
            "translation": "Venus in 11th gives wealth, many children, longevity, and fulfillment.",
            "detailed_effects": [
                "Wealth and gains",
                "Many children",
                "Long life",
                "Fulfillment of desires",
                "Social success",
                "Multiple income sources",
            ],
            "positive_effects": ["Wealth", "Many children", "Longevity", "Achievement of goals", "Gains"],
            "challenging_effects": ["Expenses on social activities"],
            "timing": "Gains increase with age",
            "tags": ["wealth", "gains", "longevity", "children"],
            "confidence": "high",
        },
        12: {
            "chapter": 11,
            "verses": "11.12",
            "translation": "Venus in 12th gives learning, skills, good spouse, and happiness.",
            "detailed_effects": [
                "Learning and wisdom",
                "Skillful and artistic",
                "Good spouse",
                "Happiness and contentment",
                "Success in foreign lands",
                "Spiritual inclinations",
            ],
            "positive_effects": ["Learning", "Skills", "Good spouse", "Happiness", "Foreign success"],
            "challenging_effects": ["Expenses on luxuries"],
            "timing": "Spiritual growth in Venus dasha",
            "tags": ["education", "skills", "marriage", "foreign"],
            "confidence": "high",
        },
    },
    "Saturn": {
        1: {
            "chapter": 12,
            "verses": "12.1",
            "translation": "Saturn in 1st makes one lame, suffering from wind diseases, poor, slow, cruel, and wicked.",
            "detailed_effects": [
                "Physical disabilities or lameness",
                "Wind-related diseases",
                "Poverty and financial struggles",
                "Slow in action",
                "Cruel or harsh nature",
                "Wicked disposition",
            ],
            "positive_effects": ["Discipline", "Perseverance", "Wisdom through hardship"],
            "challenging_effects": ["Lameness", "Wind diseases", "Poverty", "Slow action", "Cruel nature"],
            "timing": "Challenges throughout life",
            "tags": ["health", "wealth", "personality", "challenges"],
            "confidence": "high",
        },
        2: {
            "chapter": 12,
            "verses": "12.2",
            "translation": "Saturn in 2nd makes one ugly-faced, poor, bad wife, and eating bad food.",
            "detailed_effects": [
                "Unattractive facial features",
                "Poverty and financial difficulties",
                "Difficult spouse",
                "Poor dietary habits",
                "Harsh speech",
                "Family conflicts",
            ],
            "positive_effects": ["Discipline in finances", "Frugality"],
            "challenging_effects": ["Ugly face", "Poverty", "Bad wife", "Bad food", "Harsh speech"],
            "timing": "Financial struggles throughout life",
            "tags": ["wealth", "marriage", "appearance", "food"],
            "confidence": "high",
        },
        3: {
            "chapter": 12,
            "verses": "12.3",
            "translation": "Saturn in 3rd gives valor, intelligence, limited sibling happiness, and wealth.",
            "detailed_effects": [
                "Courage and perseverance",
                "Intelligence and wisdom",
                "Limited happiness from siblings",
                "Wealth through hard work",
                "Success through effort",
                "Disciplined approach",
            ],
            "positive_effects": ["Valor", "Intelligence", "Wealth through effort", "Discipline"],
            "challenging_effects": ["Limited sibling happiness", "Slow progress"],
            "timing": "Wealth through persistent effort",
            "tags": ["courage", "siblings", "wealth", "intelligence"],
            "confidence": "high",
        },
        4: {
            "chapter": 12,
            "verses": "12.4",
            "translation": "Saturn in 4th causes lack of happiness, loss of mother, property difficulties, and few vehicles.",
            "detailed_effects": [
                "Domestic unhappiness",
                "Mother's loss or separation",
                "Property difficulties",
                "Few or old vehicles",
                "Emotional coldness",
                "Heart health concerns",
            ],
            "positive_effects": ["Independence", "Self-reliance"],
            "challenging_effects": ["Unhappiness", "Mother's loss", "Property problems", "Few vehicles"],
            "timing": "Domestic challenges throughout life",
            "tags": ["mother", "property", "happiness", "vehicles"],
            "confidence": "high",
        },
        5: {
            "chapter": 12,
            "verses": "12.5",
            "translation": "Saturn in 5th gives lack of children, poverty, evil mind, and stomach diseases.",
            "detailed_effects": [
                "Childlessness or delayed children",
                "Poverty and financial struggles",
                "Evil or negative thinking",
                "Digestive problems",
                "Creative blocks",
                "Speculative losses",
            ],
            "positive_effects": ["Discipline in creative pursuits", "Philosophical wisdom"],
            "challenging_effects": ["No children", "Poverty", "Evil mind", "Stomach diseases"],
            "timing": "Children delayed or absent",
            "tags": ["children", "wealth", "health", "mind"],
            "confidence": "high",
        },
        6: {
            "chapter": 12,
            "verses": "12.6",
            "translation": "Saturn in 6th destroys enemies, gives fame, strength, and happiness.",
            "detailed_effects": [
                "Victory over enemies",
                "Fame and recognition",
                "Physical strength",
                "Happiness and contentment",
                "Success in service",
                "Disciplined work approach",
            ],
            "positive_effects": ["Defeats enemies", "Fame", "Strength", "Happiness", "Service success"],
            "challenging_effects": ["Chronic health issues if afflicted"],
            "timing": "Victory over enemies in Saturn dasha",
            "tags": ["enemies", "fame", "health", "happiness"],
            "confidence": "high",
        },
        7: {
            "chapter": 12,
            "verses": "12.7",
            "translation": "Saturn in 7th causes loss of wife, diseases, sinful acts, and unhappiness.",
            "detailed_effects": [
                "Loss of spouse or separation",
                "Chronic diseases",
                "Sinful or unethical behavior",
                "Marital discord",
                "Unhappiness",
                "Partnership difficulties",
            ],
            "positive_effects": ["Discipline in partnerships", "Long-lasting relationships when formed"],
            "challenging_effects": ["Loss of wife", "Diseases", "Sinful acts", "Unhappiness"],
            "timing": "Marriage challenges throughout life",
            "tags": ["marriage", "health", "ethics", "happiness"],
            "confidence": "high",
        },
        8: {
            "chapter": 12,
            "verses": "12.8",
            "translation": "Saturn in 8th gives short life, diseases, poverty, and physical defects.",
            "detailed_effects": [
                "Reduced longevity",
                "Chronic diseases",
                "Poverty and financial loss",
                "Physical defects",
                "Sudden crises",
                "Interest in occult",
            ],
            "positive_effects": ["Occult knowledge", "Research abilities", "Discipline in crises"],
            "challenging_effects": ["Short life", "Diseases", "Poverty", "Physical defects"],
            "timing": "Health challenges throughout life",
            "tags": ["longevity", "health", "wealth", "occult"],
            "confidence": "high",
        },
        9: {
            "chapter": 12,
            "verses": "12.9",
            "translation": "Saturn in 9th causes lack of wealth, children, wife, father hatred, and irreligious nature.",
            "detailed_effects": [
                "Poverty and financial struggles",
                "Difficulties with children",
                "Marital challenges",
                "Father conflicts",
                "Irreligious tendencies",
                "Lack of dharma",
            ],
            "positive_effects": ["Independent philosophy", "Wisdom through hardship"],
            "challenging_effects": ["Poverty", "No children", "Marital problems", "Father hatred", "Irreligious"],
            "timing": "Father-related conflicts, spiritual challenges",
            "tags": ["dharma", "father", "wealth", "children"],
            "confidence": "high",
        },
        10: {
            "chapter": 12,
            "verses": "12.10",
            "translation": "Saturn in 10th gives wealth, virtue, religious nature, and royal favor.",
            "detailed_effects": [
                "Wealth through career",
                "Virtuous character",
                "Religious inclinations",
                "Royal or government favor",
                "Authority through discipline",
                "Career success",
            ],
            "positive_effects": ["Wealth", "Virtue", "Religious nature", "Royal favor", "Authority"],
            "challenging_effects": ["Slow career progression", "Heavy responsibilities"],
            "timing": "Career success after age 36",
            "tags": ["career", "wealth", "virtue", "authority"],
            "confidence": "high",
        },
        11: {
            "chapter": 12,
            "verses": "12.11",
            "translation": "Saturn in 11th gives wealth, longevity, limited children, and fulfillment.",
            "detailed_effects": [
                "Wealth and gains",
                "Long life",
                "Few children",
                "Fulfillment of desires",
                "Social success",
                "Disciplined approach to gains",
            ],
            "positive_effects": ["Wealth", "Longevity", "Achievement of goals", "Gains"],
            "challenging_effects": ["Limited children", "Slow gains"],
            "timing": "Gains increase with age",
            "tags": ["wealth", "gains", "longevity", "children"],
            "confidence": "high",
        },
        12: {
            "chapter": 12,
            "verses": "12.12",
            "translation": "Saturn in 12th causes lack of wealth, learning, happiness, and service to others.",
            "detailed_effects": [
                "Poverty and financial losses",
                "Limited education",
                "Unhappiness and sorrow",
                "Service to others",
                "Spiritual inclinations",
                "Interest in isolation",
            ],
            "positive_effects": ["Spiritual growth", "Service to humanity", "Discipline in spiritual practices"],
            "challenging_effects": ["Poverty", "Lack of learning", "Unhappiness", "Service work"],
            "timing": "Expenses throughout life, spiritual growth later",
            "tags": ["wealth", "education", "happiness", "spirituality"],
            "confidence": "high",
        },
    },
}


def get_hora_sara_interpretation(planet: str, house: int) -> Dict[str, Any]:
    """
    Get Hora Sara interpretation for planet in house.

    Args:
        planet: Planet name
        house: House number (1-12)

    Returns:
        Dictionary with interpretation data or None if not available
    """
    planet_data = HORA_SARA_PLANETS_IN_HOUSES.get(planet, {})
    return planet_data.get(house, None)


def get_available_hora_sara_combinations() -> list:
    """Get list of available planet-house combinations in Hora Sara"""
    combinations = []
    for planet, houses in HORA_SARA_PLANETS_IN_HOUSES.items():
        for house in houses.keys():
            combinations.append({"planet": planet, "house": house})
    return combinations
