"""
Phaladeepika: Planets in Houses
================================
Digitized interpretations from Phaladeepika by Mantreswara
Chapters 10-21: Planetary placements in houses

Translation: V. Subrahmanya Sastri (1963)
Source: Ranjan Publications

Phaladeepika (Light on Results) is a classical Vedic astrology text
focusing on practical predictive techniques.
"""

from typing import Any, Dict

# Phaladeepika Chapters 10-21: Planet-in-House Interpretations

PHALADEEPIKA_PLANETS_IN_HOUSES: Dict[str, Dict[int, Dict[str, Any]]] = {
    "Sun": {
        1: {
            "chapter": 10,
            "verses": "10.1",
            "translation": "When the Sun occupies the first house, the native will have scanty hair on the head, be lazy, of a quick temper, tall, with big hands and feet, will have bile as the chief humor, and his right eye will be defective.",
            "detailed_effects": [
                "Scanty hair on head",
                "Lazy temperament",
                "Quick to anger",
                "Tall stature with large hands and feet",
                "Bilious constitution (Pitta dominant)",
                "Right eye weakness or defect",
            ],
            "positive_effects": ["Tall and commanding presence", "Strong will and determination"],
            "challenging_effects": [
                "Tendency toward laziness",
                "Quick temper and anger",
                "Eye health issues",
                "Health vulnerabilities",
            ],
            "timing": "Effects manifest throughout life, intensify during Sun dasha",
            "tags": ["personality", "health", "appearance", "temperament"],
            "confidence": "high",
        },
        2: {
            "chapter": 10,
            "verses": "10.2",
            "translation": "The Sun in the 2nd makes one scholarly but wrathful, bereft of learning and riches, without food at all times, subservient to the fair sex, and deprived of a good or a beautiful wife or blessed with a wife having the virtues of a male.",
            "detailed_effects": [
                "Scholarly but wrathful disposition",
                "Financial struggles despite education",
                "Irregular food habits",
                "Dominated by women",
                "Wife may be masculine in nature or virtues",
            ],
            "positive_effects": ["Scholarly and educated"],
            "challenging_effects": [
                "Wrathful and angry nature",
                "Financial difficulties",
                "Marital challenges",
                "Food insecurity",
            ],
            "timing": "Financial and marital effects throughout life",
            "tags": ["wealth", "speech", "personality", "marriage"],
            "confidence": "high",
        },
        3: {
            "chapter": 10,
            "verses": "10.3",
            "translation": "With the Sun in the 3rd house, one will be very powerful, energetic, very liberal, wealthy, and famous in the world. He will be free from enemies and defeated adversaries.",
            "detailed_effects": [
                "Very powerful and energetic",
                "Liberal and generous nature",
                "Wealthy and famous",
                "Victory over enemies",
                "Strong courage and initiative",
            ],
            "positive_effects": [
                "Power and energy",
                "Wealth and fame",
                "Courage and bravery",
                "Victory over adversaries",
            ],
            "challenging_effects": [],
            "timing": "Courage and initiative throughout life, peak during Sun dasha",
            "tags": ["courage", "siblings", "wealth", "fame"],
            "confidence": "high",
        },
        4: {
            "chapter": 10,
            "verses": "10.4",
            "translation": "The Sun in the 4th makes one devoid of happiness and comforts, deprived of mother, relatives, lands, vehicles, and friends. If the Sun be weak in 4th, the person will be a servant to another.",
            "detailed_effects": [
                "Lack of domestic happiness",
                "Mother's early death or separation",
                "Loss of property and vehicles",
                "Few friends or relatives",
                "Service position if Sun is weak",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Domestic unhappiness",
                "Loss of mother",
                "Property losses",
                "Social isolation",
                "Servitude if weak",
            ],
            "timing": "Mother-related effects in youth, property issues throughout",
            "tags": ["mother", "property", "happiness", "vehicles"],
            "confidence": "high",
        },
        5: {
            "chapter": 10,
            "verses": "10.5",
            "translation": "With Sun in 5th house, one will be bereft of happiness, wealth, and children. He will be intelligent, wander in forests or hilly places, and will be quick in anger.",
            "detailed_effects": [
                "Unhappiness and poverty",
                "Difficulty with children",
                "High intelligence",
                "Tendency to wander or travel",
                "Quick temper",
            ],
            "positive_effects": ["High intelligence", "Love of nature and travel"],
            "challenging_effects": [
                "Lack of happiness",
                "Financial struggles",
                "Issues with progeny",
                "Anger problems",
            ],
            "timing": "Children-related effects during procreative years",
            "tags": ["children", "intelligence", "wealth", "temperament"],
            "confidence": "high",
        },
        6: {
            "chapter": 10,
            "verses": "10.6",
            "translation": "The Sun in 6th makes one very strong, king or like a king, wealthy, victorious over enemies, stomach disorders, prone to anger.",
            "detailed_effects": [
                "Very strong physically",
                "Authority and leadership (king-like)",
                "Wealthy and prosperous",
                "Victory over adversaries",
                "Digestive issues or stomach problems",
                "Prone to anger",
            ],
            "positive_effects": [
                "Physical strength",
                "Authority and power",
                "Wealth accumulation",
                "Victory over enemies",
            ],
            "challenging_effects": ["Stomach and digestive disorders", "Anger issues"],
            "timing": "Strength and authority throughout life, health issues may develop",
            "tags": ["health", "enemies", "authority", "wealth"],
            "confidence": "high",
        },
        7: {
            "chapter": 10,
            "verses": "10.7",
            "translation": "Sun in 7th house makes one suffer humiliation, lose wife and wealth, live in foreign lands, and have a diseased body.",
            "detailed_effects": [
                "Loss of respect and dignity",
                "Marital difficulties or loss of spouse",
                "Financial losses",
                "Life in foreign places",
                "Health problems",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Humiliation and loss of dignity",
                "Marital problems",
                "Wealth losses",
                "Foreign residence",
                "Diseased constitution",
            ],
            "timing": "Marital effects after marriage, health issues throughout",
            "tags": ["marriage", "wealth", "health", "foreign"],
            "confidence": "high",
        },
        8: {
            "chapter": 10,
            "verses": "10.8",
            "translation": "With the Sun in 8th, one will be deprived of eyesight, without wealth, friendless, without a good heart, living by other people, and short-lived.",
            "detailed_effects": [
                "Eye problems or blindness",
                "Poverty and financial struggles",
                "Few or no friends",
                "Lacking compassion",
                "Dependent on others",
                "Reduced longevity",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Vision loss",
                "Financial dependency",
                "Social isolation",
                "Hard-hearted nature",
                "Short lifespan",
            ],
            "timing": "Challenges throughout life, longevity concerns in later years",
            "tags": ["longevity", "wealth", "health", "eyes"],
            "confidence": "high",
        },
        9: {
            "chapter": 10,
            "verses": "10.9",
            "translation": "The Sun in 9th makes one bereft of riches, children, and wife. He will not be inclined to religious deeds and will hate his father.",
            "detailed_effects": [
                "Financial difficulties",
                "Issues with children",
                "Marital problems",
                "Lack of religious inclination",
                "Conflict with father",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Poverty",
                "Loss of progeny",
                "Marital discord",
                "Irreligious tendencies",
                "Father-son conflict",
            ],
            "timing": "Father-related effects in youth, dharma issues throughout",
            "tags": ["dharma", "father", "children", "wealth"],
            "confidence": "high",
        },
        10: {
            "chapter": 10,
            "verses": "10.10",
            "translation": "With the Sun in 10th, one will be happy, capable, intelligent, wealthy, famous, will do virtuous deeds, blessed with vehicles and land.",
            "detailed_effects": [
                "Happiness and contentment",
                "High capability and competence",
                "Intelligent and wise",
                "Wealth accumulation",
                "Fame and recognition",
                "Virtuous character and actions",
                "Property and vehicles",
            ],
            "positive_effects": [
                "Career excellence",
                "Fame and recognition",
                "Wealth and prosperity",
                "Virtuous nature",
                "Property ownership",
            ],
            "challenging_effects": [],
            "timing": "Career peaks during Sun mahadasha, recognition throughout life",
            "tags": ["career", "fame", "wealth", "virtue"],
            "confidence": "high",
        },
        11: {
            "chapter": 10,
            "verses": "10.11",
            "translation": "The Sun in 11th makes one wealthy, long-lived, blessed with children, few diseases, brave, with income from multiple sources.",
            "detailed_effects": [
                "Substantial wealth",
                "Long life",
                "Good children",
                "Strong health (minimal diseases)",
                "Courageous nature",
                "Multiple income streams",
            ],
            "positive_effects": [
                "Wealth and prosperity",
                "Longevity",
                "Healthy progeny",
                "Good health",
                "Courage",
                "Diverse income",
            ],
            "challenging_effects": [],
            "timing": "Wealth gains throughout life, peak during Sun dasha",
            "tags": ["wealth", "gains", "longevity", "children"],
            "confidence": "high",
        },
        12: {
            "chapter": 10,
            "verses": "10.12",
            "translation": "With the Sun in 12th, one will be defective in a limb, deprived of eyesight, will lose wealth through royal displeasure or enemies, will live in a foreign land, and be bereft of wife and children.",
            "detailed_effects": [
                "Physical defects or disability",
                "Eye problems or blindness",
                "Financial losses through authority/enemies",
                "Life away from homeland",
                "Loss of spouse and children",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Physical disabilities",
                "Vision loss",
                "Wealth losses",
                "Foreign residence",
                "Loss of family",
            ],
            "timing": "Challenges throughout life, losses in later years",
            "tags": ["losses", "foreign", "health", "marriage"],
            "confidence": "high",
        },
    },
    "Moon": {
        1: {
            "chapter": 11,
            "verses": "11.1",
            "translation": "Moon in 1st makes one fickle-minded, given to drinking water often, handsome, with wealth from liquids, kind-hearted, soft-spoken.",
            "detailed_effects": [
                "Changeable and fickle mind",
                "Frequent thirst",
                "Attractive appearance",
                "Income from liquids/water businesses",
                "Kind and compassionate",
                "Soft and pleasant speech",
            ],
            "positive_effects": [
                "Beautiful appearance",
                "Kind-hearted nature",
                "Soft speech",
                "Wealth from water-related activities",
            ],
            "challenging_effects": ["Mental fickleness", "Changeable moods", "Excessive thirst"],
            "timing": "Effects prominent throughout life, intensify during Moon dasha",
            "tags": ["personality", "appearance", "wealth", "temperament"],
            "confidence": "high",
        },
        2: {
            "chapter": 11,
            "verses": "11.2",
            "translation": "Moon in 2nd gives beautiful face, sweet speech, wealth, good food, large family.",
            "detailed_effects": [
                "Beautiful facial features",
                "Sweet and melodious speech",
                "Wealth accumulation",
                "Enjoyment of good food",
                "Large and prosperous family",
            ],
            "positive_effects": [
                "Attractive face",
                "Pleasant speech",
                "Financial prosperity",
                "Good food and nourishment",
                "Large family",
            ],
            "challenging_effects": [],
            "timing": "Wealth gains during Moon dasha, family growth throughout",
            "tags": ["wealth", "speech", "family", "appearance"],
            "confidence": "high",
        },
        3: {
            "chapter": 11,
            "verses": "11.3",
            "translation": "Moon in 3rd makes one cruel, miserly, proud, devoted to relatives, brave.",
            "detailed_effects": [
                "Cruel or harsh nature",
                "Miserly with money",
                "Proud and arrogant",
                "Strong devotion to siblings/relatives",
                "Courageous and brave",
            ],
            "positive_effects": ["Courage and bravery", "Devotion to family"],
            "challenging_effects": ["Cruel tendencies", "Miserliness", "Pride and arrogance"],
            "timing": "Sibling relationships important throughout life",
            "tags": ["courage", "siblings", "temperament", "wealth"],
            "confidence": "high",
        },
        4: {
            "chapter": 11,
            "verses": "11.4",
            "translation": "The Moon in the 4th house bestows happiness, friendship, enjoyment of comforts, possession of conveyances, and acquisition of wealth.",
            "detailed_effects": [
                "Domestic happiness and peace",
                "Comfortable home environment",
                "Vehicles and properties",
                "Emotional fulfillment from family",
                "Strong connection with mother",
                "Good friendships",
            ],
            "positive_effects": [
                "Domestic bliss",
                "Material comforts",
                "Property and vehicles",
                "Emotional security",
                "Wealth accumulation",
                "Strong friendships",
            ],
            "challenging_effects": [],
            "timing": "Home acquisition during Moon dasha, family happiness throughout",
            "tags": ["mother", "property", "happiness", "vehicles"],
            "confidence": "high",
        },
        5: {
            "chapter": 11,
            "verses": "11.5",
            "translation": "Moon in 5th gives good intelligence, many sons, devotion to Shiva, happiness.",
            "detailed_effects": [
                "High intelligence and wisdom",
                "Blessed with many sons",
                "Devotion to Lord Shiva",
                "General happiness and contentment",
                "Creative and imaginative mind",
            ],
            "positive_effects": ["Intelligence", "Good progeny", "Spiritual devotion", "Happiness", "Creativity"],
            "challenging_effects": [],
            "timing": "Children born during Moon dasha, intelligence throughout",
            "tags": ["children", "intelligence", "spirituality", "happiness"],
            "confidence": "high",
        },
        6: {
            "chapter": 11,
            "verses": "11.6",
            "translation": "Moon in 6th gives laziness, stomach ailments, many enemies, mental distress.",
            "detailed_effects": [
                "Lazy temperament",
                "Digestive and stomach problems",
                "Many adversaries and enemies",
                "Mental anxiety and distress",
                "Health challenges",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Laziness",
                "Stomach disorders",
                "Enemy problems",
                "Mental distress",
                "Health issues",
            ],
            "timing": "Health issues may develop, enemy conflicts throughout",
            "tags": ["health", "enemies", "mental_health", "temperament"],
            "confidence": "high",
        },
        7: {
            "chapter": 11,
            "verses": "11.7",
            "translation": "Moon in 7th gives beautiful spouse, passionate nature, wealth, travels, diseases from water.",
            "detailed_effects": [
                "Beautiful and attractive spouse",
                "Passionate and romantic nature",
                "Wealth accumulation",
                "Frequent travels",
                "Water-related health issues",
            ],
            "positive_effects": ["Beautiful partner", "Passionate nature", "Wealth", "Travel opportunities"],
            "challenging_effects": ["Water-related diseases", "Excessive passion may cause issues"],
            "timing": "Marriage during Moon dasha, travel throughout life",
            "tags": ["marriage", "wealth", "travel", "health"],
            "confidence": "high",
        },
        8: {
            "chapter": 11,
            "verses": "11.8",
            "translation": "Moon in 8th makes one diseased, sorrowful, dependent on others, short-lived.",
            "detailed_effects": [
                "Chronic diseases",
                "Sorrow and grief",
                "Financial dependency",
                "Reduced longevity",
                "Emotional suffering",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Health problems",
                "Mental sorrow",
                "Dependency on others",
                "Short lifespan",
                "Emotional pain",
            ],
            "timing": "Health challenges throughout, longevity concerns in later years",
            "tags": ["longevity", "health", "sorrow", "dependency"],
            "confidence": "high",
        },
        9: {
            "chapter": 11,
            "verses": "11.9",
            "translation": "Moon in 9th gives wealth, virtuous nature, devotion to deities, happiness from father.",
            "detailed_effects": [
                "Wealth and prosperity",
                "Virtuous and righteous character",
                "Devotion to gods and spirituality",
                "Good relationship with father",
                "Fortune and blessings",
            ],
            "positive_effects": [
                "Wealth",
                "Virtue and righteousness",
                "Spiritual devotion",
                "Father's blessings",
                "Good fortune",
            ],
            "challenging_effects": [],
            "timing": "Fortune throughout life, spiritual growth during Moon dasha",
            "tags": ["dharma", "father", "wealth", "spirituality"],
            "confidence": "high",
        },
        10: {
            "chapter": 11,
            "verses": "11.10",
            "translation": "Moon in 10th gives success in undertakings, intelligence, fame, virtuous deeds, respect.",
            "detailed_effects": [
                "Success in professional endeavors",
                "High intelligence",
                "Fame and recognition",
                "Virtuous actions",
                "Social respect and honor",
            ],
            "positive_effects": ["Career success", "Intelligence", "Fame", "Virtue", "Respect"],
            "challenging_effects": [],
            "timing": "Career success during Moon dasha, recognition throughout",
            "tags": ["career", "fame", "intelligence", "virtue"],
            "confidence": "high",
        },
        11: {
            "chapter": 11,
            "verses": "11.11",
            "translation": "Moon in 11th gives wealth, long life, good children, few diseases, many friends.",
            "detailed_effects": [
                "Substantial wealth and gains",
                "Long lifespan",
                "Good and virtuous children",
                "Strong health",
                "Large network of friends",
            ],
            "positive_effects": ["Wealth and gains", "Longevity", "Good progeny", "Health", "Friendships"],
            "challenging_effects": [],
            "timing": "Gains throughout life, peak during Moon dasha",
            "tags": ["wealth", "gains", "longevity", "children"],
            "confidence": "high",
        },
        12: {
            "chapter": 11,
            "verses": "11.12",
            "translation": "Moon in 12th gives eye defects, enmity with mother, expenditure, residence in foreign lands.",
            "detailed_effects": [
                "Eye problems or defects",
                "Conflict with mother",
                "Heavy expenditures",
                "Life in foreign countries",
                "Losses and expenses",
            ],
            "positive_effects": ["Spiritual inclinations", "Foreign opportunities"],
            "challenging_effects": [
                "Eye health issues",
                "Mother-child conflict",
                "Financial losses",
                "Foreign residence",
            ],
            "timing": "Expenses throughout, foreign residence possible",
            "tags": ["losses", "foreign", "health", "mother"],
            "confidence": "high",
        },
    },
    "Mars": {
        1: {
            "chapter": 12,
            "verses": "12.1",
            "translation": "Mars in 1st house makes one cruel, adventurous, eater of forbidden food, quarrelsome, has a scarred body, and unkind to mother.",
            "detailed_effects": [
                "Cruel or harsh temperament",
                "Adventurous and risk-taking nature",
                "Dietary indiscretions",
                "Quarrelsome and aggressive",
                "Physical scars or marks on body",
                "Strained relationship with mother",
            ],
            "positive_effects": ["Courage and bravery", "Adventurous spirit", "Physical strength"],
            "challenging_effects": ["Cruel tendencies", "Quarrelsome nature", "Physical scars", "Conflict with mother"],
            "timing": "Aggressive tendencies throughout life, peak during Mars dasha",
            "tags": ["personality", "aggression", "health", "mother"],
            "confidence": "high",
        },
        2: {
            "chapter": 12,
            "verses": "12.2",
            "translation": "Mars in 2nd causes eye disease, loss of wealth, harsh speech, living on others' food, family conflicts.",
            "detailed_effects": [
                "Eye problems or defects",
                "Financial losses",
                "Harsh or abusive speech",
                "Dependent on others for sustenance",
                "Family disputes and conflicts",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Eye health issues",
                "Wealth losses",
                "Harsh speech",
                "Food dependency",
                "Family conflicts",
            ],
            "timing": "Financial and speech issues throughout life",
            "tags": ["wealth", "speech", "health", "family"],
            "confidence": "high",
        },
        3: {
            "chapter": 12,
            "verses": "12.3",
            "translation": "Mars in 3rd gives courage, wealth, happiness from brothers, leadership, and victory over enemies.",
            "detailed_effects": [
                "Exceptional courage and bravery",
                "Wealth accumulation",
                "Good relationship with siblings",
                "Leadership qualities",
                "Victory over adversaries",
            ],
            "positive_effects": ["Courage", "Wealth", "Sibling harmony", "Leadership", "Victory over enemies"],
            "challenging_effects": [],
            "timing": "Courage and leadership throughout life",
            "tags": ["courage", "siblings", "wealth", "leadership"],
            "confidence": "high",
        },
        4: {
            "chapter": 12,
            "verses": "12.4",
            "translation": "Mars in 4th destroys happiness, mother, lands, vehicles, relatives, and comforts.",
            "detailed_effects": [
                "Loss of domestic happiness",
                "Harm to mother or early separation",
                "Property losses",
                "Loss of vehicles",
                "Few relatives or strained relations",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Domestic unhappiness",
                "Mother's suffering",
                "Property losses",
                "Vehicle losses",
                "Relative conflicts",
            ],
            "timing": "Mother-related effects in youth, property issues throughout",
            "tags": ["mother", "property", "happiness", "vehicles"],
            "confidence": "high",
        },
        5: {
            "chapter": 12,
            "verses": "12.5",
            "translation": "Mars in 5th makes one devoid of happiness, wealth, and children; intelligent but wrathful.",
            "detailed_effects": [
                "Unhappiness and discontent",
                "Financial struggles",
                "Difficulty with children or childlessness",
                "High intelligence",
                "Quick temper and anger",
            ],
            "positive_effects": ["High intelligence"],
            "challenging_effects": ["Unhappiness", "Poverty", "Children issues", "Anger problems"],
            "timing": "Children-related effects during procreative years",
            "tags": ["children", "intelligence", "wealth", "temperament"],
            "confidence": "high",
        },
        6: {
            "chapter": 12,
            "verses": "12.6",
            "translation": "Mars in 6th gives wealth, victory over enemies, happiness, strong physique, and leadership.",
            "detailed_effects": [
                "Substantial wealth",
                "Victory over adversaries",
                "Overall happiness",
                "Strong and healthy body",
                "Leadership and authority",
            ],
            "positive_effects": ["Wealth", "Victory over enemies", "Happiness", "Physical strength", "Leadership"],
            "challenging_effects": [],
            "timing": "Strength and victory throughout life",
            "tags": ["health", "enemies", "wealth", "leadership"],
            "confidence": "high",
            "notes": "Mars in 6th (Upachaya) is very strong and favorable",
        },
        7: {
            "chapter": 12,
            "verses": "12.7",
            "translation": "Mars in 7th causes loss of spouse, wealth problems, diseases, and living in foreign lands.",
            "detailed_effects": [
                "Marital difficulties or loss of spouse",
                "Financial problems",
                "Health issues and diseases",
                "Life away from homeland",
                "Conflicts in partnerships",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Marital problems",
                "Wealth issues",
                "Health problems",
                "Foreign residence",
                "Partnership conflicts",
            ],
            "timing": "Marital effects after marriage, health issues throughout",
            "tags": ["marriage", "wealth", "health", "foreign"],
            "confidence": "high",
            "notes": "Mars in 7th (Kuja Dosha) harms marriage and partnerships",
        },
        8: {
            "chapter": 12,
            "verses": "12.8",
            "translation": "Mars in 8th gives eye defects, loss of wealth, friendless, dependent on others, short life.",
            "detailed_effects": [
                "Eye problems",
                "Poverty and financial struggles",
                "Lack of friends",
                "Dependent on others",
                "Reduced longevity",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Eye defects",
                "Financial losses",
                "Social isolation",
                "Dependency",
                "Short lifespan",
            ],
            "timing": "Challenges throughout life, longevity concerns",
            "tags": ["longevity", "wealth", "health", "eyes"],
            "confidence": "high",
        },
        9: {
            "chapter": 12,
            "verses": "12.9",
            "translation": "Mars in 9th destroys father, dharma, fortune, and makes one sinful and irreligious.",
            "detailed_effects": [
                "Harm to father or conflict",
                "Lack of fortune and luck",
                "Irreligious tendencies",
                "Sinful actions",
                "Obstacles in dharma",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Father's suffering",
                "Loss of fortune",
                "Irreligious nature",
                "Sinful tendencies",
                "Dharma obstacles",
            ],
            "timing": "Father-related effects in youth, dharma issues throughout",
            "tags": ["dharma", "father", "fortune", "spirituality"],
            "confidence": "high",
        },
        10: {
            "chapter": 12,
            "verses": "12.10",
            "translation": "Mars in 10th gives wealth, happiness, leadership, fame, courage, and virtuous deeds.",
            "detailed_effects": [
                "Wealth and prosperity",
                "Career success and leadership",
                "Fame and recognition",
                "Exceptional courage",
                "Virtuous actions",
            ],
            "positive_effects": ["Wealth", "Career success", "Fame", "Courage", "Virtue"],
            "challenging_effects": [],
            "timing": "Career peaks during Mars dasha",
            "tags": ["career", "fame", "wealth", "leadership"],
            "confidence": "high",
            "notes": "Mars in 10th (Kendra/Kona) is very strong for career",
        },
        11: {
            "chapter": 12,
            "verses": "12.11",
            "translation": "Mars in 11th gives wealth, long life, happiness, gains from multiple sources, and courage.",
            "detailed_effects": [
                "Substantial wealth and gains",
                "Long life",
                "Overall happiness",
                "Multiple income streams",
                "Courageous nature",
            ],
            "positive_effects": ["Wealth and gains", "Longevity", "Happiness", "Multiple incomes", "Courage"],
            "challenging_effects": [],
            "timing": "Gains throughout life, peak during Mars dasha",
            "tags": ["wealth", "gains", "longevity", "courage"],
            "confidence": "high",
        },
        12: {
            "chapter": 12,
            "verses": "12.12",
            "translation": "Mars in 12th causes eye defects, loss of wealth through enemies, living abroad, and physical suffering.",
            "detailed_effects": [
                "Eye problems",
                "Financial losses through adversaries",
                "Life in foreign lands",
                "Physical suffering and diseases",
                "Expenses and losses",
            ],
            "positive_effects": [],
            "challenging_effects": [
                "Eye defects",
                "Wealth losses",
                "Foreign residence",
                "Physical suffering",
                "Heavy expenses",
            ],
            "timing": "Losses and expenses throughout life",
            "tags": ["losses", "foreign", "health", "eyes"],
            "confidence": "high",
        },
    },
    "Mercury": {
        1: {
            "chapter": 13,
            "verses": "13.1",
            "translation": "Mercury in 1st makes one skilled in arts, eloquent in speech, intelligent, long-lived, with beautiful eyes.",
            "detailed_effects": [
                "Exceptional communication skills",
                "Artistic and creative abilities",
                "Sharp intellect and quick learning",
                "Attractive features, especially eyes",
                "Longevity and good health",
            ],
            "positive_effects": ["Eloquence", "Intelligence", "Artistic talents", "Longevity", "Beautiful eyes"],
            "challenging_effects": [],
            "timing": "Intellectual pursuits throughout life",
            "tags": ["intelligence", "communication", "arts", "longevity"],
            "confidence": "high",
        },
        2: {
            "chapter": 13,
            "verses": "13.2",
            "translation": "Mercury in 2nd gives wealth, sweet speech, good education, happiness from family.",
            "detailed_effects": [
                "Wealth accumulation",
                "Sweet and pleasant speech",
                "Good education",
                "Family happiness",
                "Financial prosperity",
            ],
            "positive_effects": ["Wealth", "Sweet speech", "Education", "Family harmony"],
            "challenging_effects": [],
            "timing": "Wealth gains during Mercury dasha",
            "tags": ["wealth", "speech", "education", "family"],
            "confidence": "high",
        },
        3: {
            "chapter": 13,
            "verses": "13.3",
            "translation": "Mercury in 3rd gives courage, wealth, happiness from siblings, intelligence, and success.",
            "detailed_effects": [
                "Courage and initiative",
                "Wealth through communication",
                "Good sibling relationships",
                "High intelligence",
                "Success in endeavors",
            ],
            "positive_effects": ["Courage", "Wealth", "Sibling harmony", "Intelligence", "Success"],
            "challenging_effects": [],
            "timing": "Communication skills peak during Mercury dasha",
            "tags": ["courage", "siblings", "wealth", "intelligence"],
            "confidence": "high",
        },
        4: {
            "chapter": 13,
            "verses": "13.4",
            "translation": "Mercury in 4th gives happiness, education, mother's blessings, property, vehicles, and comforts.",
            "detailed_effects": [
                "Domestic happiness",
                "Good education",
                "Mother's blessings",
                "Property ownership",
                "Vehicles and comforts",
            ],
            "positive_effects": ["Happiness", "Education", "Mother's grace", "Property", "Vehicles"],
            "challenging_effects": [],
            "timing": "Property acquisition during Mercury dasha",
            "tags": ["mother", "property", "education", "happiness"],
            "confidence": "high",
        },
        5: {
            "chapter": 13,
            "verses": "13.5",
            "translation": "Mercury in 5th gives intelligence, good children, wealth, happiness, and success in speculation.",
            "detailed_effects": [
                "Exceptional intelligence",
                "Good and intelligent children",
                "Wealth accumulation",
                "Overall happiness",
                "Success in speculation/investments",
            ],
            "positive_effects": ["Intelligence", "Good progeny", "Wealth", "Happiness", "Speculation success"],
            "challenging_effects": [],
            "timing": "Children and investments during Mercury dasha",
            "tags": ["children", "intelligence", "wealth", "speculation"],
            "confidence": "high",
        },
        6: {
            "chapter": 13,
            "verses": "13.6",
            "translation": "Mercury in 6th gives victory over enemies, wealth, good health, intelligence, and leadership.",
            "detailed_effects": [
                "Victory over adversaries",
                "Wealth accumulation",
                "Good health",
                "High intelligence",
                "Leadership abilities",
            ],
            "positive_effects": ["Victory over enemies", "Wealth", "Health", "Intelligence", "Leadership"],
            "challenging_effects": [],
            "timing": "Success throughout life",
            "tags": ["health", "enemies", "wealth", "intelligence"],
            "confidence": "high",
        },
        7: {
            "chapter": 13,
            "verses": "13.7",
            "translation": "Mercury in 7th gives beautiful spouse, happiness in marriage, wealth, intelligence, and diplomatic skills.",
            "detailed_effects": [
                "Beautiful and intelligent spouse",
                "Marital happiness",
                "Wealth through partnerships",
                "High intelligence",
                "Diplomatic and negotiation skills",
            ],
            "positive_effects": ["Beautiful spouse", "Marital bliss", "Wealth", "Intelligence", "Diplomacy"],
            "challenging_effects": [],
            "timing": "Marriage during Mercury dasha",
            "tags": ["marriage", "wealth", "intelligence", "diplomacy"],
            "confidence": "high",
        },
        8: {
            "chapter": 13,
            "verses": "13.8",
            "translation": "Mercury in 8th gives long life, fame, wealth from inheritance, occult knowledge.",
            "detailed_effects": [
                "Long lifespan",
                "Fame and recognition",
                "Wealth through inheritance",
                "Occult and mystical knowledge",
                "Research abilities",
            ],
            "positive_effects": ["Longevity", "Fame", "Inheritance", "Occult knowledge"],
            "challenging_effects": [],
            "timing": "Occult interests during Mercury dasha",
            "tags": ["longevity", "wealth", "occult", "fame"],
            "confidence": "high",
        },
        9: {
            "chapter": 13,
            "verses": "13.9",
            "translation": "Mercury in 9th gives wealth, virtue, devotion to deities, father's blessings, and fortune.",
            "detailed_effects": [
                "Wealth and prosperity",
                "Virtuous character",
                "Religious devotion",
                "Father's blessings",
                "Good fortune",
            ],
            "positive_effects": ["Wealth", "Virtue", "Devotion", "Father's grace", "Fortune"],
            "challenging_effects": [],
            "timing": "Fortune throughout life",
            "tags": ["dharma", "father", "wealth", "spirituality"],
            "confidence": "high",
        },
        10: {
            "chapter": 13,
            "verses": "13.10",
            "translation": "Mercury in 10th gives intelligence, fame, success in career, wealth, and virtuous deeds.",
            "detailed_effects": [
                "Exceptional intelligence",
                "Fame and recognition",
                "Career success",
                "Wealth accumulation",
                "Virtuous actions",
            ],
            "positive_effects": ["Intelligence", "Fame", "Career success", "Wealth", "Virtue"],
            "challenging_effects": [],
            "timing": "Career peaks during Mercury dasha",
            "tags": ["career", "fame", "intelligence", "wealth"],
            "confidence": "high",
        },
        11: {
            "chapter": 13,
            "verses": "13.11",
            "translation": "Mercury in 11th bestows learning, wealth, happiness, many sources of income, and fulfillment of desires.",
            "detailed_effects": [
                "Educational achievements",
                "Substantial wealth",
                "Overall happiness",
                "Multiple income streams",
                "Desire fulfillment",
            ],
            "positive_effects": ["Education", "Wealth", "Happiness", "Multiple incomes", "Desires fulfilled"],
            "challenging_effects": [],
            "timing": "Gains throughout life, peak during Mercury dasha",
            "tags": ["wealth", "gains", "education", "happiness"],
            "confidence": "high",
        },
        12: {
            "chapter": 13,
            "verses": "13.12",
            "translation": "Mercury in 12th gives expenses, losses, life abroad, but also learning and spiritual knowledge.",
            "detailed_effects": [
                "Heavy expenditures",
                "Financial losses",
                "Life in foreign lands",
                "Learning and education",
                "Spiritual knowledge",
            ],
            "positive_effects": ["Learning", "Spiritual knowledge", "Foreign opportunities"],
            "challenging_effects": ["Expenses", "Losses", "Foreign residence"],
            "timing": "Expenses throughout, spiritual growth during Mercury dasha",
            "tags": ["losses", "foreign", "education", "spirituality"],
            "confidence": "high",
        },
    },
    "Jupiter": {
        1: {
            "chapter": 14,
            "verses": "14.3",
            "translation": "Jupiter in the first house makes one learned, virtuous, long-lived, firm in friendship, of good conduct, and having many sons.",
            "detailed_effects": [
                "Wisdom and scholarly pursuits",
                "Ethical and virtuous nature",
                "Long and prosperous life",
                "Loyal friendships",
                "Blessed with children",
            ],
            "positive_effects": [
                "Wisdom and learning",
                "Virtuous character",
                "Longevity",
                "Good children",
                "Loyal friends",
            ],
            "challenging_effects": ["May be overly optimistic at times", "Tendency toward weight gain"],
            "timing": "Spiritual growth and wisdom during Jupiter dasha",
        },
        2: {
            "chapter": 14,
            "verses": "14.4",
            "translation": "Jupiter in the 2nd house makes one wealthy, learned, eloquent in speech, handsome-faced, and blessed with good food and family.",
            "detailed_effects": [
                "Substantial wealth accumulation",
                "Eloquent and wise speech",
                "Beautiful facial features",
                "Good education and learning",
                "Happy family life",
                "Enjoyment of good food",
            ],
            "positive_effects": [
                "Wealth and prosperity",
                "Eloquent speech",
                "Beautiful face",
                "Learning and wisdom",
                "Family happiness",
            ],
            "challenging_effects": ["May overindulge in food", "Can be overly optimistic about finances"],
            "timing": "Wealth increases during Jupiter dasha",
            "tags": ["wealth", "speech", "family", "learning"],
            "confidence": "high",
        },
        3: {
            "chapter": 14,
            "verses": "14.5",
            "translation": "Jupiter in the 3rd makes one courageous, wealthy, intelligent, but with limited happiness from siblings.",
            "detailed_effects": [
                "Courage and initiative",
                "Wealth through self-effort",
                "Intelligence and wisdom",
                "Limited sibling harmony",
                "Success in communications",
                "Teaching abilities",
            ],
            "positive_effects": [
                "Courage and bravery",
                "Wealth through effort",
                "Intelligence",
                "Communication skills",
                "Teaching talents",
            ],
            "challenging_effects": ["Limited happiness from siblings", "Sibling conflicts possible"],
            "timing": "Courage and wealth develop during Jupiter dasha",
            "tags": ["courage", "siblings", "wealth", "intelligence"],
            "confidence": "high",
        },
        4: {
            "chapter": 14,
            "verses": "14.6",
            "translation": "Jupiter in the 4th bestows happiness, property, vehicles, learning, and blessings from mother.",
            "detailed_effects": [
                "Domestic happiness and peace",
                "Property and land ownership",
                "Vehicles and conveyances",
                "Good education",
                "Mother's blessings",
                "Comfortable home life",
            ],
            "positive_effects": [
                "Domestic happiness",
                "Property and vehicles",
                "Good education",
                "Mother's grace",
                "Comfortable living",
            ],
            "challenging_effects": ["May be too attached to comforts"],
            "timing": "Property gains during Jupiter dasha",
            "tags": ["property", "mother", "education", "happiness"],
            "confidence": "high",
        },
        5: {
            "chapter": 14,
            "verses": "14.7",
            "translation": "Jupiter in the 5th gives good children, intelligence, wisdom, success in speculation, and spiritual knowledge.",
            "detailed_effects": [
                "Blessed with intelligent children",
                "Wisdom and good judgment",
                "Success in speculation",
                "Spiritual knowledge",
                "Creative intelligence",
                "Good fortune",
            ],
            "positive_effects": [
                "Good children",
                "Intelligence and wisdom",
                "Speculative gains",
                "Spiritual knowledge",
                "Fortune",
            ],
            "challenging_effects": ["May be overly optimistic in speculation"],
            "timing": "Children during Jupiter dasha, spiritual growth",
            "tags": ["children", "intelligence", "speculation", "spirituality"],
            "confidence": "high",
        },
        6: {
            "chapter": 14,
            "verses": "14.8",
            "translation": "Jupiter in the 6th destroys enemies, brings fame, but gives limited happiness from children and some financial challenges.",
            "detailed_effects": [
                "Victory over enemies",
                "Fame and recognition",
                "Success in service professions",
                "Limited happiness from children",
                "Some financial difficulties",
                "Health generally good",
            ],
            "positive_effects": ["Defeats enemies", "Fame", "Success in service", "Good health", "Victory in disputes"],
            "challenging_effects": ["Limited happiness from children", "Financial challenges", "Work-related stress"],
            "timing": "Victory over enemies during Jupiter dasha",
            "tags": ["enemies", "fame", "service", "health"],
            "confidence": "high",
        },
        7: {
            "chapter": 14,
            "verses": "14.9",
            "translation": "Jupiter in the 7th bestows a beautiful and virtuous spouse, happiness in marriage, wealth, and success in partnerships.",
            "detailed_effects": [
                "Beautiful and virtuous spouse",
                "Marital happiness",
                "Wealth through partnerships",
                "Success in business partnerships",
                "Diplomatic abilities",
                "Good fortune",
            ],
            "positive_effects": [
                "Excellent marriage",
                "Beautiful spouse",
                "Partnership success",
                "Wealth",
                "Diplomatic skills",
            ],
            "challenging_effects": ["May have high expectations from spouse"],
            "timing": "Marriage during Jupiter dasha, partnership success",
            "tags": ["marriage", "partnerships", "wealth", "spouse"],
            "confidence": "high",
        },
        8: {
            "chapter": 14,
            "verses": "14.10",
            "translation": "Jupiter in the 8th gives longevity, interest in occult, some financial challenges, but spiritual wisdom and transformative experiences.",
            "detailed_effects": [
                "Long life",
                "Interest in occult sciences",
                "Financial ups and downs",
                "Spiritual wisdom",
                "Transformative experiences",
                "Research abilities",
            ],
            "positive_effects": [
                "Longevity",
                "Spiritual wisdom",
                "Occult knowledge",
                "Transformative growth",
                "Research skills",
            ],
            "challenging_effects": ["Financial instability", "Sudden changes", "Inheritance issues"],
            "timing": "Spiritual transformation during Jupiter dasha",
            "tags": ["longevity", "occult", "transformation", "spirituality"],
            "confidence": "high",
        },
        9: {
            "chapter": 14,
            "verses": "14.11",
            "translation": "Jupiter in the 9th house makes one fortunate, wealthy, learned in scriptures, religious, and blessed with father's grace.",
            "detailed_effects": [
                "Exceptional fortune and blessings",
                "Wealth from righteous means",
                "Deep spiritual knowledge",
                "Good relationship with father",
                "Religious and philosophical inclinations",
            ],
            "positive_effects": [
                "Exceptional fortune",
                "Wealth and prosperity",
                "Spiritual wisdom",
                "Father's blessings",
                "Religious inclination",
            ],
            "challenging_effects": ["May be overly idealistic"],
            "timing": "Fortune manifests during Jupiter dasha, pilgrimage during this period",
        },
        10: {
            "chapter": 14,
            "verses": "14.12",
            "translation": "Jupiter in the 10th gives authority, career success, fame, virtuous conduct, and respect in society.",
            "detailed_effects": [
                "Outstanding career success",
                "Authority and leadership",
                "Fame and recognition",
                "Virtuous professional conduct",
                "Respect from society",
                "Government favor",
            ],
            "positive_effects": ["Career excellence", "Authority", "Fame", "Virtuous conduct", "Social respect"],
            "challenging_effects": ["High expectations from career", "Pressure to maintain status"],
            "timing": "Career peaks during Jupiter dasha",
            "tags": ["career", "authority", "fame", "virtue"],
            "confidence": "high",
        },
        11: {
            "chapter": 14,
            "verses": "14.13",
            "translation": "Jupiter in the 11th bestows wealth, many children, longevity, fulfillment of desires, and social success.",
            "detailed_effects": [
                "Substantial wealth and gains",
                "Many children",
                "Long and healthy life",
                "Fulfillment of desires",
                "Social success",
                "Multiple income sources",
            ],
            "positive_effects": [
                "Wealth and prosperity",
                "Many children",
                "Longevity",
                "Achievement of goals",
                "Social success",
            ],
            "challenging_effects": ["May be overly optimistic about gains"],
            "timing": "Gains increase during Jupiter dasha",
            "tags": ["wealth", "gains", "children", "longevity"],
            "confidence": "high",
        },
        12: {
            "chapter": 14,
            "verses": "14.14",
            "translation": "Jupiter in the 12th gives spiritual inclination, expenses on good causes, success in foreign lands, but limited wealth and some losses.",
            "detailed_effects": [
                "Spiritual inclinations",
                "Charitable nature",
                "Success in foreign lands",
                "Expenses on good causes",
                "Limited wealth",
                "Interest in meditation",
            ],
            "positive_effects": [
                "Spiritual growth",
                "Charitable nature",
                "Foreign success",
                "Wisdom",
                "Moksha orientation",
            ],
            "challenging_effects": ["Financial losses", "Expenses exceed income", "Limited material wealth"],
            "timing": "Spiritual growth during Jupiter dasha, foreign travel",
            "tags": ["spirituality", "expenses", "foreign", "charity"],
            "confidence": "high",
        },
    },
    "Venus": {
        1: {
            "chapter": 15,
            "verses": "15.1",
            "translation": "Venus in 1st bestows beauty, attractive eyes, happiness, poetic nature, enjoyment of pleasures, and good fortune.",
            "detailed_effects": [
                "Physical beauty and charm",
                "Attractive eyes",
                "Happiness and contentment",
                "Poetic and artistic nature",
                "Enjoyment of life's pleasures",
                "Good fortune",
            ],
            "positive_effects": ["Beauty", "Charm", "Happiness", "Artistic talents", "Fortune"],
            "challenging_effects": [],
            "timing": "Romance and arts throughout life",
            "tags": ["beauty", "arts", "happiness", "fortune"],
            "confidence": "high",
        },
        2: {
            "chapter": 15,
            "verses": "15.2",
            "translation": "Venus in 2nd gives wealth, sweet speech, beautiful face, good food, and family happiness.",
            "detailed_effects": [
                "Substantial wealth",
                "Sweet and melodious speech",
                "Beautiful facial features",
                "Enjoyment of good food",
                "Family happiness",
            ],
            "positive_effects": ["Wealth", "Sweet speech", "Beauty", "Good food", "Family harmony"],
            "challenging_effects": [],
            "timing": "Wealth gains during Venus dasha",
            "tags": ["wealth", "speech", "family", "beauty"],
            "confidence": "high",
        },
        3: {
            "chapter": 15,
            "verses": "15.3",
            "translation": "Venus in 3rd gives courage, happiness from siblings, wealth, artistic talents, and success.",
            "detailed_effects": [
                "Courage and initiative",
                "Good sibling relationships",
                "Wealth accumulation",
                "Artistic and creative talents",
                "Success in endeavors",
            ],
            "positive_effects": ["Courage", "Sibling harmony", "Wealth", "Arts", "Success"],
            "challenging_effects": [],
            "timing": "Artistic success during Venus dasha",
            "tags": ["courage", "siblings", "wealth", "arts"],
            "confidence": "high",
        },
        4: {
            "chapter": 15,
            "verses": "15.4",
            "translation": "Venus in 4th gives happiness, mother's blessings, property, vehicles, comforts, and education.",
            "detailed_effects": [
                "Domestic happiness",
                "Mother's blessings",
                "Property and land",
                "Vehicles and conveyances",
                "Material comforts",
                "Good education",
            ],
            "positive_effects": ["Happiness", "Mother's grace", "Property", "Vehicles", "Comforts", "Education"],
            "challenging_effects": [],
            "timing": "Property acquisition during Venus dasha",
            "tags": ["mother", "property", "happiness", "vehicles"],
            "confidence": "high",
        },
        5: {
            "chapter": 15,
            "verses": "15.5",
            "translation": "Venus in 5th gives good children, intelligence, wealth, happiness, and success in speculation.",
            "detailed_effects": [
                "Good and beautiful children",
                "High intelligence",
                "Wealth accumulation",
                "Overall happiness",
                "Success in speculation",
            ],
            "positive_effects": ["Good progeny", "Intelligence", "Wealth", "Happiness", "Speculation success"],
            "challenging_effects": [],
            "timing": "Children during Venus dasha",
            "tags": ["children", "intelligence", "wealth", "happiness"],
            "confidence": "high",
        },
        6: {
            "chapter": 15,
            "verses": "15.6",
            "translation": "Venus in 6th gives victory over enemies, wealth, good health, and happiness.",
            "detailed_effects": [
                "Victory over adversaries",
                "Wealth accumulation",
                "Good health",
                "Overall happiness",
                "Success in service",
            ],
            "positive_effects": ["Victory over enemies", "Wealth", "Health", "Happiness"],
            "challenging_effects": [],
            "timing": "Success throughout life",
            "tags": ["health", "enemies", "wealth", "happiness"],
            "confidence": "high",
        },
        7: {
            "chapter": 15,
            "verses": "15.7",
            "translation": "Venus in 7th gives beautiful and virtuous spouse, happiness in marriage, and gains through partnerships.",
            "detailed_effects": [
                "Beautiful and virtuous spouse",
                "Harmonious marital life",
                "Success through partnerships",
                "Diplomatic abilities",
                "Material gains from marriage",
            ],
            "positive_effects": [
                "Beautiful spouse",
                "Marital happiness",
                "Partnership success",
                "Diplomacy",
                "Wealth from marriage",
            ],
            "challenging_effects": [],
            "timing": "Marriage during Venus dasha",
            "tags": ["marriage", "wealth", "partnerships", "happiness"],
            "confidence": "high",
        },
        8: {
            "chapter": 15,
            "verses": "15.8",
            "translation": "Venus in 8th gives long life, wealth from inheritance, occult knowledge, and mystical interests.",
            "detailed_effects": [
                "Long lifespan",
                "Wealth through inheritance",
                "Occult and mystical knowledge",
                "Interest in mysteries",
                "Research abilities",
            ],
            "positive_effects": ["Longevity", "Inheritance", "Occult knowledge", "Mystical interests"],
            "challenging_effects": [],
            "timing": "Inheritance during Venus dasha",
            "tags": ["longevity", "wealth", "occult", "inheritance"],
            "confidence": "high",
        },
        9: {
            "chapter": 15,
            "verses": "15.9",
            "translation": "Venus in 9th gives wealth, virtue, devotion, father's blessings, fortune, and happiness.",
            "detailed_effects": [
                "Wealth and prosperity",
                "Virtuous character",
                "Religious devotion",
                "Father's blessings",
                "Good fortune",
                "Overall happiness",
            ],
            "positive_effects": ["Wealth", "Virtue", "Devotion", "Father's grace", "Fortune", "Happiness"],
            "challenging_effects": [],
            "timing": "Fortune throughout life",
            "tags": ["dharma", "father", "wealth", "happiness"],
            "confidence": "high",
        },
        10: {
            "chapter": 15,
            "verses": "15.10",
            "translation": "Venus in 10th gives fame, success in career, wealth, happiness, and virtuous deeds.",
            "detailed_effects": [
                "Fame and recognition",
                "Career success",
                "Wealth accumulation",
                "Overall happiness",
                "Virtuous actions",
            ],
            "positive_effects": ["Fame", "Career success", "Wealth", "Happiness", "Virtue"],
            "challenging_effects": [],
            "timing": "Career peaks during Venus dasha",
            "tags": ["career", "fame", "wealth", "happiness"],
            "confidence": "high",
        },
        11: {
            "chapter": 15,
            "verses": "15.11",
            "translation": "Venus in 11th gives wealth, happiness, gains from multiple sources, and fulfillment of desires.",
            "detailed_effects": [
                "Substantial wealth and gains",
                "Overall happiness",
                "Multiple income streams",
                "Desire fulfillment",
                "Social success",
            ],
            "positive_effects": [
                "Wealth and gains",
                "Happiness",
                "Multiple incomes",
                "Desires fulfilled",
                "Social connections",
            ],
            "challenging_effects": [],
            "timing": "Gains throughout life",
            "tags": ["wealth", "gains", "happiness", "desires"],
            "confidence": "high",
        },
        12: {
            "chapter": 15,
            "verses": "15.12",
            "translation": "Venus in 12th gives expenses on luxuries, life abroad, spiritual inclinations, but also losses.",
            "detailed_effects": [
                "Expenditure on luxuries",
                "Life in foreign lands",
                "Spiritual inclinations",
                "Financial losses",
                "Comfort-seeking nature",
            ],
            "positive_effects": ["Spiritual growth", "Foreign opportunities", "Luxury enjoyment"],
            "challenging_effects": ["Heavy expenses", "Financial losses", "Foreign residence"],
            "timing": "Expenses throughout, spiritual growth during Venus dasha",
            "tags": ["losses", "foreign", "spirituality", "luxury"],
            "confidence": "high",
        },
    },
    "Saturn": {
        1: {
            "chapter": 16,
            "verses": "16.3",
            "translation": "Saturn in the first house makes one lame, suffering from wind diseases, poor, slow in action, cruel, and of wicked disposition.",
            "detailed_effects": [
                "Serious and disciplined nature",
                "Potential health challenges",
                "Slow but steady approach",
                "Hardworking disposition",
                "Challenges in early life",
            ],
            "positive_effects": [
                "Discipline and perseverance",
                "Depth of character",
                "Ability to endure hardships",
                "Wisdom through experience",
            ],
            "challenging_effects": [
                "Health vulnerabilities",
                "Slow progress",
                "Pessimistic tendencies",
                "Early life difficulties",
            ],
            "timing": "Challenges in youth, improvement during and after Saturn dasha",
        },
        2: {
            "chapter": 16,
            "verses": "16.4",
            "translation": "Saturn in the 2nd house makes one poor, ugly-faced, devoid of learning, with harsh speech, and eating bad food.",
            "detailed_effects": [
                "Financial challenges",
                "Unattractive facial features",
                "Limited formal education",
                "Harsh or slow speech",
                "Poor dietary habits",
                "Family difficulties",
            ],
            "positive_effects": [
                "Discipline in finances",
                "Frugality and careful resource management",
                "Wisdom in speech when mature",
            ],
            "challenging_effects": [
                "Financial difficulties",
                "Ugly face",
                "Lack of education",
                "Harsh speech",
                "Poor food quality",
            ],
            "timing": "Financial struggles early, improvement after age 36",
            "tags": ["wealth", "speech", "family", "education"],
            "confidence": "high",
        },
        3: {
            "chapter": 16,
            "verses": "16.5",
            "translation": "Saturn in the 3rd gives courage, wealth through effort, intelligence, but limited happiness from siblings.",
            "detailed_effects": [
                "Courage and perseverance",
                "Wealth through hard work",
                "Intelligence and discipline",
                "Limited sibling harmony",
                "Success through self-effort",
                "Long-term initiatives",
            ],
            "positive_effects": [
                "Courage and perseverance",
                "Wealth through effort",
                "Intelligence",
                "Disciplined approach",
                "Self-made success",
            ],
            "challenging_effects": ["Limited happiness from siblings", "Sibling loss or conflicts", "Slow progress"],
            "timing": "Wealth develops slowly through persistent effort",
            "tags": ["courage", "siblings", "wealth", "effort"],
            "confidence": "high",
        },
        4: {
            "chapter": 16,
            "verses": "16.6",
            "translation": "Saturn in the 4th causes lack of domestic happiness, loss of mother, property difficulties, and few vehicles.",
            "detailed_effects": [
                "Domestic challenges",
                "Mother's early loss or separation",
                "Property difficulties",
                "Few or old vehicles",
                "Emotional distance from family",
                "Heart health concerns",
            ],
            "positive_effects": [
                "Independence and self-reliance",
                "Discipline in domestic matters",
                "Property gains after age 36",
            ],
            "challenging_effects": [
                "Lack of domestic happiness",
                "Mother's loss",
                "Property problems",
                "Few vehicles",
                "Emotional coldness",
            ],
            "timing": "Domestic challenges throughout life, property gains delayed",
            "tags": ["mother", "property", "happiness", "vehicles"],
            "confidence": "high",
        },
        5: {
            "chapter": 16,
            "verses": "16.7",
            "translation": "Saturn in the 5th gives difficulties with children, financial challenges, pessimistic thinking, and digestive problems.",
            "detailed_effects": [
                "Childlessness or delayed children",
                "Financial difficulties",
                "Pessimistic mindset",
                "Digestive health issues",
                "Creative blocks",
                "Speculative losses",
            ],
            "positive_effects": [
                "Discipline in creative pursuits",
                "Philosophical wisdom",
                "Adopted children may bring happiness",
            ],
            "challenging_effects": [
                "Lack of children",
                "Financial problems",
                "Negative thinking",
                "Stomach diseases",
                "Unhappiness",
            ],
            "timing": "Children delayed or absent, financial struggles",
            "tags": ["children", "wealth", "health", "creativity"],
            "confidence": "high",
        },
        6: {
            "chapter": 16,
            "verses": "16.8",
            "translation": "Saturn in the 6th destroys enemies, brings fame, good health, and success through service and discipline.",
            "detailed_effects": [
                "Victory over enemies",
                "Fame and recognition",
                "Strong health",
                "Success in service professions",
                "Disciplined work approach",
                "Longevity",
            ],
            "positive_effects": ["Defeats enemies", "Fame", "Good health", "Success in service", "Discipline"],
            "challenging_effects": ["Chronic health issues if afflicted", "Slow victory", "Work stress"],
            "timing": "Victory over enemies during Saturn dasha",
            "tags": ["enemies", "fame", "health", "service"],
            "confidence": "high",
        },
        7: {
            "chapter": 16,
            "verses": "16.9",
            "translation": "Saturn in the 7th causes marital difficulties, loss of spouse, health problems, and partnership challenges.",
            "detailed_effects": [
                "Marital challenges",
                "Loss of spouse or separation",
                "Late marriage",
                "Health issues",
                "Partnership difficulties",
                "Chronic diseases",
            ],
            "positive_effects": [
                "Discipline in partnerships",
                "Long-lasting relationships when formed",
                "Success with mature partners",
            ],
            "challenging_effects": [
                "Loss of wife",
                "Marital discord",
                "Chronic diseases",
                "Partnership conflicts",
                "Unhappiness",
            ],
            "timing": "Marriage challenges, late marriage common",
            "tags": ["marriage", "partnerships", "health", "spouse"],
            "confidence": "high",
        },
        8: {
            "chapter": 16,
            "verses": "16.10",
            "translation": "Saturn in the 8th gives reduced longevity, chronic diseases, financial difficulties, and physical defects.",
            "detailed_effects": [
                "Chronic health concerns",
                "Reduced longevity if afflicted",
                "Financial instability",
                "Physical defects",
                "Interest in occult",
                "Inheritance issues",
            ],
            "positive_effects": [
                "Deep research abilities",
                "Occult knowledge",
                "Transformative wisdom",
                "Discipline in crises",
            ],
            "challenging_effects": [
                "Short lifespan",
                "Chronic diseases",
                "Financial problems",
                "Physical defects",
                "Sudden losses",
            ],
            "timing": "Health challenges throughout life",
            "tags": ["longevity", "health", "wealth", "occult"],
            "confidence": "high",
        },
        9: {
            "chapter": 16,
            "verses": "16.11",
            "translation": "Saturn in the 9th causes difficulties with father, lack of spiritual inclination, financial struggles, and marital problems.",
            "detailed_effects": [
                "Strained relationship with father",
                "Lack of religious inclination",
                "Financial difficulties",
                "Marital challenges",
                "Difficulties with children",
                "Foreign travel problems",
            ],
            "positive_effects": [
                "Independent philosophy",
                "Discipline in spiritual pursuits when mature",
                "Wisdom through hardship",
            ],
            "challenging_effects": [
                "Father's loss or separation",
                "Financial problems",
                "Marital difficulties",
                "Lack of spirituality",
                "Unhappiness",
            ],
            "timing": "Father-related issues, spiritual awakening delayed",
            "tags": ["father", "spirituality", "wealth", "marriage"],
            "confidence": "high",
        },
        10: {
            "chapter": 16,
            "verses": "16.12",
            "translation": "Saturn in the 10th house bestows authority, leadership, success through perseverance, gains from agriculture, and respect in society.",
            "detailed_effects": [
                "Authority and leadership roles",
                "Success through hard work",
                "Gains from land and agriculture",
                "Social respect and recognition",
                "Sustained career growth",
            ],
            "positive_effects": [
                "Authority and power",
                "Career success through effort",
                "Land and property gains",
                "Social respect",
                "Leadership abilities",
            ],
            "challenging_effects": ["Slow career progression", "Heavy responsibilities", "Delays in recognition"],
            "timing": "Authority peaks during Saturn dasha, recognition in later life",
        },
        11: {
            "chapter": 16,
            "verses": "16.13",
            "translation": "Saturn in the 11th bestows wealth through effort, longevity, few children, and fulfillment of desires through discipline.",
            "detailed_effects": [
                "Wealth through hard work",
                "Long and healthy life",
                "Few but responsible children",
                "Gains through discipline",
                "Social success",
                "Multiple income sources",
            ],
            "positive_effects": [
                "Wealth and gains",
                "Longevity",
                "Achievement of goals",
                "Social success",
                "Disciplined approach",
            ],
            "challenging_effects": ["Limited children", "Slow gains", "Serious friendships"],
            "timing": "Gains increase with age, prosperity after 36",
            "tags": ["wealth", "gains", "longevity", "children"],
            "confidence": "high",
        },
        12: {
            "chapter": 16,
            "verses": "16.14",
            "translation": "Saturn in the 12th causes financial losses, limited education, unhappiness, and service to others.",
            "detailed_effects": [
                "Financial losses and expenses",
                "Limited formal education",
                "Unhappiness and sorrow",
                "Service to others",
                "Spiritual inclinations develop",
                "Interest in isolation",
            ],
            "positive_effects": [
                "Spiritual growth",
                "Service to humanity",
                "Success in foreign lands",
                "Discipline in spiritual practices",
            ],
            "challenging_effects": [
                "Financial difficulties",
                "Lack of education",
                "Unhappiness",
                "Serving others",
                "Expenses and losses",
            ],
            "timing": "Expenses throughout life, spiritual growth in later years",
            "tags": ["expenses", "spirituality", "foreign", "service"],
            "confidence": "high",
        },
    },
}


def get_phaladeepika_interpretation(planet: str, house: int) -> Dict[str, Any]:
    """
    Get Phaladeepika interpretation for planet in house.

    Args:
        planet: Planet name
        house: House number (1-12)

    Returns:
        Dictionary with interpretation data or None if not available
    """
    planet_data = PHALADEEPIKA_PLANETS_IN_HOUSES.get(planet, {})
    return planet_data.get(house, None)


def get_available_phaladeepika_combinations() -> list:
    """Get list of available planet-house combinations in Phaladeepika"""
    combinations = []
    for planet, houses in PHALADEEPIKA_PLANETS_IN_HOUSES.items():
        for house in houses.keys():
            combinations.append({"planet": planet, "house": house})
    return combinations
